// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the ACES Project.
// Generated by scripts/generate-aces.py from pinned CTL; do not edit.
import type { ODTParams } from './aces-core'
export const ACES_DATA_BYTES = 25168
export function packAces(p: ODTParams): Float32Array<ArrayBuffer> {
  const result = new Float32Array(6292)
  result[0 * 4] = p.peakLuminance
  p.input_params.MATRIX_RGB_to_CAM16_c.forEach((row, i) => result.set(row, (1 + i) * 4))
  p.input_params.MATRIX_CAM16_c_to_RGB.forEach((row, i) => result.set(row, (4 + i) * 4))
  p.input_params.MATRIX_cone_response_to_Aab.forEach((row, i) => result.set(row, (7 + i) * 4))
  p.input_params.MATRIX_Aab_to_cone_response.forEach((row, i) => result.set(row, (10 + i) * 4))
  result[13 * 4] = p.input_params.F_L_n
  result[14 * 4] = p.input_params.cz
  result[15 * 4] = p.input_params.inv_cz
  result[16 * 4] = p.input_params.A_w_J
  result[17 * 4] = p.input_params.inv_A_w_J
  p.reach_params.MATRIX_RGB_to_CAM16_c.forEach((row, i) => result.set(row, (18 + i) * 4))
  p.reach_params.MATRIX_CAM16_c_to_RGB.forEach((row, i) => result.set(row, (21 + i) * 4))
  p.reach_params.MATRIX_cone_response_to_Aab.forEach((row, i) => result.set(row, (24 + i) * 4))
  p.reach_params.MATRIX_Aab_to_cone_response.forEach((row, i) => result.set(row, (27 + i) * 4))
  result[30 * 4] = p.reach_params.F_L_n
  result[31 * 4] = p.reach_params.cz
  result[32 * 4] = p.reach_params.inv_cz
  result[33 * 4] = p.reach_params.A_w_J
  result[34 * 4] = p.reach_params.inv_A_w_J
  p.limit_params.MATRIX_RGB_to_CAM16_c.forEach((row, i) => result.set(row, (35 + i) * 4))
  p.limit_params.MATRIX_CAM16_c_to_RGB.forEach((row, i) => result.set(row, (38 + i) * 4))
  p.limit_params.MATRIX_cone_response_to_Aab.forEach((row, i) => result.set(row, (41 + i) * 4))
  p.limit_params.MATRIX_Aab_to_cone_response.forEach((row, i) => result.set(row, (44 + i) * 4))
  result[47 * 4] = p.limit_params.F_L_n
  result[48 * 4] = p.limit_params.cz
  result[49 * 4] = p.limit_params.inv_cz
  result[50 * 4] = p.limit_params.A_w_J
  result[51 * 4] = p.limit_params.inv_A_w_J
  result[52 * 4] = p.ts.n
  result[53 * 4] = p.ts.n_r
  result[54 * 4] = p.ts.g
  result[55 * 4] = p.ts.t_1
  result[56 * 4] = p.ts.c_t
  result[57 * 4] = p.ts.s_2
  result[58 * 4] = p.ts.u_2
  result[59 * 4] = p.ts.m_2
  result[60 * 4] = p.ts.forward_limit
  result[61 * 4] = p.ts.inverse_limit
  result[62 * 4] = p.ts.log_peak
  result[63 * 4] = p.limit_J_max
  result[64 * 4] = p.model_gamma_inv
  p.TABLE_reach_M.forEach((v, i) => (result[(65 + i) * 4] = v))
  result[427 * 4] = p.sat
  result[428 * 4] = p.sat_thr
  result[429 * 4] = p.compr
  result[430 * 4] = p.chroma_compress_scale
  result[431 * 4] = p.mid_J
  result[432 * 4] = p.focus_dist
  result[433 * 4] = p.lower_hull_gamma_inv
  p.TABLE_hues.forEach((v, i) => (result[(434 + i) * 4] = v))
  p.TABLE_gamut_cusps.forEach((row, i) => result.set(row, (796 + i) * 4))
  p.TABLE_upper_hull_gamma.forEach((v, i) => (result[(1158 + i) * 4] = v))
  result.set(p.hue_linearity_search_range, 1520 * 4)
  p.input_params.MATRIX_RGB_to_CAM16_c.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1522 + i) * 4,
    ),
  )
  p.input_params.MATRIX_CAM16_c_to_RGB.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1525 + i) * 4,
    ),
  )
  p.input_params.MATRIX_cone_response_to_Aab.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1528 + i) * 4,
    ),
  )
  p.input_params.MATRIX_Aab_to_cone_response.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1531 + i) * 4,
    ),
  )
  result[1534 * 4] = p.input_params.F_L_n - Math.fround(p.input_params.F_L_n)
  result[1535 * 4] = p.input_params.cz - Math.fround(p.input_params.cz)
  result[1536 * 4] = p.input_params.inv_cz - Math.fround(p.input_params.inv_cz)
  result[1537 * 4] = p.input_params.A_w_J - Math.fround(p.input_params.A_w_J)
  result[1538 * 4] = p.input_params.inv_A_w_J - Math.fround(p.input_params.inv_A_w_J)
  p.reach_params.MATRIX_RGB_to_CAM16_c.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1539 + i) * 4,
    ),
  )
  p.reach_params.MATRIX_CAM16_c_to_RGB.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1542 + i) * 4,
    ),
  )
  p.reach_params.MATRIX_cone_response_to_Aab.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1545 + i) * 4,
    ),
  )
  p.reach_params.MATRIX_Aab_to_cone_response.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1548 + i) * 4,
    ),
  )
  result[1551 * 4] = p.reach_params.F_L_n - Math.fround(p.reach_params.F_L_n)
  result[1552 * 4] = p.reach_params.cz - Math.fround(p.reach_params.cz)
  result[1553 * 4] = p.reach_params.inv_cz - Math.fround(p.reach_params.inv_cz)
  result[1554 * 4] = p.reach_params.A_w_J - Math.fround(p.reach_params.A_w_J)
  result[1555 * 4] = p.reach_params.inv_A_w_J - Math.fround(p.reach_params.inv_A_w_J)
  p.limit_params.MATRIX_RGB_to_CAM16_c.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1556 + i) * 4,
    ),
  )
  p.limit_params.MATRIX_CAM16_c_to_RGB.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1559 + i) * 4,
    ),
  )
  p.limit_params.MATRIX_cone_response_to_Aab.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1562 + i) * 4,
    ),
  )
  p.limit_params.MATRIX_Aab_to_cone_response.forEach((row, i) =>
    result.set(
      row.map((v) => v - Math.fround(v)),
      (1565 + i) * 4,
    ),
  )
  result[1568 * 4] = p.limit_params.F_L_n - Math.fround(p.limit_params.F_L_n)
  result[1569 * 4] = p.limit_params.cz - Math.fround(p.limit_params.cz)
  result[1570 * 4] = p.limit_params.inv_cz - Math.fround(p.limit_params.inv_cz)
  result[1571 * 4] = p.limit_params.A_w_J - Math.fround(p.limit_params.A_w_J)
  result[1572 * 4] = p.limit_params.inv_A_w_J - Math.fround(p.limit_params.inv_A_w_J)
  return result
}
