// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the ACES Project.
// Generated by scripts/generate-aces.py from pinned CTL; do not edit.
import { AP0_TO_AP1, AP1_TO_AP0 } from './aces-core'
const matrix = (m: number[][]) =>
  'mat3x3f(' +
  m
    .map(
      (r) =>
        'vec3f(' + r.map((v) => (String(v).includes('.') ? String(v) : v + '.0')).join(',') + ')',
    )
    .join(',') +
  ')'
const acesMatrices =
  'const AP0_TO_AP1=' + matrix(AP0_TO_AP1) + ';\nconst AP1_TO_AP0=' + matrix(AP1_TO_AP0) + ';'
export const acesWgsl = `
// Compensated scalar products reduce cancellation near the gamut boundary.
// frexp/ldexp form a rounding boundary on fast-math Metal backends.
fn acesRound(v:f32)->f32 {let p=frexp(v);return ldexp(p.fract,p.exp);}
fn acesSum(a:f32,b:f32)->vec2f {let s=acesRound(a+b);let z=acesRound(s-a);return vec2f(s,acesRound(a-acesRound(s-z))+acesRound(b-z));}
fn acesDot(a:vec3f,b:vec3f)->f32 {
  let p=a*b; let e=fma(a,b,-p);
  let s=acesSum(p.x,p.y);let t=acesSum(s.x,p.z);
  return t.x+(s.y+t.y+e.x+e.y+e.z);
}
fn mult_f3_f33(v:vec3f,m:mat3x3f)->vec3f {
  return vec3f(acesDot(v,vec3f(m[0].x,m[1].x,m[2].x)),acesDot(v,vec3f(m[0].y,m[1].y,m[2].y)),acesDot(v,vec3f(m[0].z,m[1].z,m[2].z)));
}
fn clamp_f3(v:vec3f,lo:f32,hi:f32)->vec3f {return clamp(v,vec3f(lo),vec3f(hi));}
fn lerp(a:f32,b:f32,t:f32)->f32 {return a+t*(b-a);}
fn copysign(x:f32,y:f32)->f32 {return sign(y)*abs(x);}
fn degrees_to_radians(v:f32)->f32 {return v/180.*3.141592653589793;}
fn radians_to_degrees(v:f32)->f32 {return dsValue(dsMul(ds(v),vec2f(57.29577951308232,-6.688024427603523e-7)));}
fn acesLog10(v:f32)->f32 {return log(v)/log(10.);}
struct AcesData { values:array<vec4f,1573> }
@group(0) @binding(4) var<storage,read> acesData:AcesData;
fn aces_input_params()->JMhParams { return JMhParams(mat3x3f(acesData.values[1].xyz,acesData.values[2].xyz,acesData.values[3].xyz),mat3x3f(acesData.values[4].xyz,acesData.values[5].xyz,acesData.values[6].xyz),mat3x3f(acesData.values[7].xyz,acesData.values[8].xyz,acesData.values[9].xyz),mat3x3f(acesData.values[10].xyz,acesData.values[11].xyz,acesData.values[12].xyz),acesData.values[13].x,acesData.values[14].x,acesData.values[15].x,acesData.values[16].x,acesData.values[17].x,mat3x3f(acesData.values[1522].xyz,acesData.values[1523].xyz,acesData.values[1524].xyz),mat3x3f(acesData.values[1525].xyz,acesData.values[1526].xyz,acesData.values[1527].xyz),mat3x3f(acesData.values[1528].xyz,acesData.values[1529].xyz,acesData.values[1530].xyz),mat3x3f(acesData.values[1531].xyz,acesData.values[1532].xyz,acesData.values[1533].xyz),acesData.values[1534].x,acesData.values[1535].x,acesData.values[1536].x,acesData.values[1537].x,acesData.values[1538].x); }
fn aces_limit_params()->JMhParams { return JMhParams(mat3x3f(acesData.values[35].xyz,acesData.values[36].xyz,acesData.values[37].xyz),mat3x3f(acesData.values[38].xyz,acesData.values[39].xyz,acesData.values[40].xyz),mat3x3f(acesData.values[41].xyz,acesData.values[42].xyz,acesData.values[43].xyz),mat3x3f(acesData.values[44].xyz,acesData.values[45].xyz,acesData.values[46].xyz),acesData.values[47].x,acesData.values[48].x,acesData.values[49].x,acesData.values[50].x,acesData.values[51].x,mat3x3f(acesData.values[1556].xyz,acesData.values[1557].xyz,acesData.values[1558].xyz),mat3x3f(acesData.values[1559].xyz,acesData.values[1560].xyz,acesData.values[1561].xyz),mat3x3f(acesData.values[1562].xyz,acesData.values[1563].xyz,acesData.values[1564].xyz),mat3x3f(acesData.values[1565].xyz,acesData.values[1566].xyz,acesData.values[1567].xyz),acesData.values[1568].x,acesData.values[1569].x,acesData.values[1570].x,acesData.values[1571].x,acesData.values[1572].x); }
fn aces_ts()->TSParams { return TSParams(acesData.values[52].x,acesData.values[53].x,acesData.values[54].x,acesData.values[55].x,acesData.values[56].x,acesData.values[57].x,acesData.values[58].x,acesData.values[59].x,acesData.values[60].x,acesData.values[61].x,acesData.values[62].x); }
struct TSParams {n:f32,
n_r:f32,
g:f32,
t_1:f32,
c_t:f32,
s_2:f32,
u_2:f32,
m_2:f32,
forward_limit:f32,
inverse_limit:f32,
log_peak:f32}
struct JMhParams {MATRIX_RGB_to_CAM16_c:mat3x3f,
MATRIX_CAM16_c_to_RGB:mat3x3f,
MATRIX_cone_response_to_Aab:mat3x3f,
MATRIX_Aab_to_cone_response:mat3x3f,
F_L_n:f32,
cz:f32,
inv_cz:f32,
A_w_J:f32,
inv_A_w_J:f32,
MATRIX_RGB_to_CAM16_c_lo:mat3x3f,
MATRIX_CAM16_c_to_RGB_lo:mat3x3f,
MATRIX_cone_response_to_Aab_lo:mat3x3f,
MATRIX_Aab_to_cone_response_lo:mat3x3f,
F_L_n_lo:f32,
cz_lo:f32,
inv_cz_lo:f32,
A_w_J_lo:f32,
inv_A_w_J_lo:f32}
struct HueDependentGamutParams {JMcusp:vec2f,
gamma_bottom_inv:f32,
gamma_top_inv:f32,
focus_J:f32,
analytical_threshold:f32}
const tableSize:i32=360;
const additionalTableEntries:i32=2;
const totalTableSize:i32=tableSize + additionalTableEntries;
const baseIndex:i32=1;
const hue_limit:f32=360.;
const cuspCornerCount:i32=6;
const totalCornerCount:i32=cuspCornerCount + 2;
const max_sorted_corners:i32=2 * cuspCornerCount;
const reach_cusp_tolerance:f32=1e-3;
const display_cusp_tolerance:f32=1e-7;
const gamma_minimum:f32=0.0;
const gamma_maximum:f32=5.0;
const gamma_search_step:f32=0.4;
const gamma_accuracy:f32=1e-5;
const ref_luminance:f32=100.;
const L_A:f32=100.;
const Y_b:f32=20.;
const surround=vec3f(.9,.59,.9);
const J_scale:f32=100.0;
const cam_nl_Y_reference:f32=100.0;
const cam_nl_offset:f32=0.2713 * cam_nl_Y_reference;
const cam_nl_scale:f32=4.0 * cam_nl_Y_reference;
const model_gamma:f32=surround[1] * (1.48 + sqrt(Y_b / ref_luminance));
const chroma_compress:f32=2.4;
const chroma_compress_fact:f32=3.3;
const chroma_expand:f32=1.3;
const chroma_expand_fact:f32=0.69;
const chroma_expand_thr:f32=0.5;
const smooth_cusps:f32=0.12;
const smooth_m:f32=0.27;
const cusp_mid_blend:f32=1.3;
const focus_gain_blend:f32=0.3;
const focus_adjust_gain:f32=0.55;
const focus_distance:f32=1.35;
const focus_distance_scaling:f32=1.75;
const compression_threshold:f32=0.75;
const test_count:i32=5;
${acesMatrices}
fn tonescale_fwd(x:f32,params:TSParams)->f32 {

	
	var f:f32=params.m_2 * acesPow(max(0.0, x) / (x + params.s_2), params.g);
	var h:f32=max(0., f * f / (f + params.t_1)); 

	return h * params.n_r; 

}
fn wrap_to_360(hue:f32)->f32 {

    var y:f32=(hue % 360.);
    if (y < 0.)
    {
        y=y + 360.;
    }
    return y;

}
fn hue_position_in_uniform_table(hue:f32,table_size:i32)->i32 {

    var wrapped_hue:f32=wrap_to_360(hue);
    var result:i32=i32((wrapped_hue / hue_limit * f32(table_size)));
    return result;

}
fn _post_adaptation_cone_response_compression_fwd(Rc:f32)->f32 {

    var F_L_Y:f32=acesPow(Rc, 0.42);
    var Ra:f32=(F_L_Y) / (cam_nl_offset + F_L_Y);
    return Ra;

}
fn _post_adaptation_cone_response_compression_inv(Ra:f32)->f32 {

    var Ra_lim:f32=min(Ra, 0.99);
    var F_L_Y:f32=(cam_nl_offset * Ra_lim) / (1. - Ra_lim);
    var Rc:f32=acesPow(F_L_Y, 1. / 0.42);
    return Rc;

}
fn post_adaptation_cone_response_compression_fwd(v:f32)->f32 {

    var abs_v:f32=abs(v);
    var Ra:f32=_post_adaptation_cone_response_compression_fwd(abs_v);
    return copysign(Ra, v);

}
fn post_adaptation_cone_response_compression_inv(v:f32)->f32 {

    var abs_v:f32=abs(v);
    var Rc:f32=_post_adaptation_cone_response_compression_inv(abs_v);
    return copysign(Rc, v);

}
fn Achromatic_n_to_J(A:f32,cz:f32)->f32 {

    return J_scale * acesPow(A, cz);

}
fn J_to_Achromatic_n(J:f32,inv_cz:f32)->f32 {

    return acesPow(J * (1. / J_scale), inv_cz);

}
fn _A_to_Y(A:f32,p:JMhParams)->f32 {

    var Ra:f32=p.A_w_J * A;
    var Y:f32=_post_adaptation_cone_response_compression_inv(Ra) / p.F_L_n;

    return Y;

}
fn RGB_to_JMh(RGB:vec3f,p:JMhParams)->vec3f {

    var Aab:vec3f=RGB_to_Aab(RGB, p);
    var JMh:vec3f=Aab_to_JMh(Aab, p);

    return JMh;

}
fn JMh_to_RGB(JMh:vec3f,p:JMhParams)->vec3f {

    var Aab:vec3f=JMh_to_Aab(JMh, p);
    var rgb:vec3f=Aab_to_RGB(Aab, p);
    return rgb;

}
fn clamp_AP0_to_AP1(aces:vec3f,clamp_lower_limit:f32,clamp_upper_limit:f32)->vec3f {

    var AP1:vec3f=mult_f3_f33(aces, AP0_TO_AP1);
    var AP1_clamped:vec3f=clamp_f3(AP1, clamp_lower_limit, clamp_upper_limit);
    var AP0_clamped:vec3f=mult_f3_f33(AP1_clamped, AP1_TO_AP0);

    return AP0_clamped;

}
fn reach_M_from_table(h:f32)->f32 {

    var base:i32=i32(hue_position_in_uniform_table(h, tableSize));
    var t:f32=h - f32(base);
    var i_lo:i32=i32(base + baseIndex);
    var i_hi:i32=i32(i_lo + 1);

    return lerp(acesData.values[65+i_lo].x, acesData.values[65+i_hi].x, t);

}
fn reinhard_remap(scale:f32,nd:f32)->f32 {

    if (false)
    {
        if (nd >= 1.0)
        {
            return scale;
        }
        else
        {
            return scale * -(nd / (nd - 1.));
        }
    }
    return scale * nd / (1. + nd);

}
fn midpoint(low:f32,high:f32)->f32 {

    return (low + high) / 2.;

}
fn toe(x:f32,limit:f32,k1_in:f32,k2_in:f32)->f32 {

    if (x > limit) { return x; }

    var k2:f32=max(k2_in, 0.001);
    var k1:f32=sqrt(k1_in * k1_in + k2 * k2);
    var k3:f32=(limit + k1) / (limit + k2);

    if (false)
    {
        return (x * x + k1 * x) / (k3 * (x + k2));
    }
    else
    {
        var minus_b:f32=k3 * x - k1;
        var minus_c:f32=k2 * k3 * x;
        return 0.5 * (minus_b + sqrt(minus_b * minus_b + 4. * minus_c));
    }

}
fn chroma_compress_norm(h:f32,chroma_compress_scale:f32)->f32 {

    var hr:f32=degrees_to_radians(h);

    var a:f32=cos(hr);
    var b:f32=sin(hr);
    var cos_hr2:f32=a * a - b * b;
    var sin_hr2:f32=2.0 * a * b;
    var cos_hr3:f32=4.0 * a * a * a - 3.0 * a;
    var sin_hr3:f32=3.0 * b - 4.0 * b * b * b;

    var M:f32=11.34072 * a +
              16.46899 * cos_hr2 +
              7.88380 * cos_hr3 +
              14.66441 * b +
              -6.37224 * sin_hr2 +
              9.19364 * sin_hr3 +
              77.12896;

    return M * chroma_compress_scale;

}
fn chroma_compress_fwd(JMh:vec3f,tonemapped_J:f32)->vec3f {

    var J:f32=JMh[0];
    var M:f32=JMh[1];
    var h:f32=JMh[2];

    var M_compr:f32=M;

    if (M != 0.0)
    {
        var nJ:f32=tonemapped_J / acesData.values[63].x;
        var snJ:f32=max(0., 1. - nJ);
        var Mnorm:f32=chroma_compress_norm(h, acesData.values[430].x);
        var limit:f32=acesPow(nJ, acesData.values[64].x) * reach_M_from_table(h) / Mnorm;

        var toe_limit:f32=limit - 0.001;
        var toe_snJ_sat:f32=snJ * acesData.values[427].x;
        var toe_sqrt_nJ_sat_thr:f32=sqrt(nJ * nJ + acesData.values[428].x);
        var toe_nJ_compr:f32=nJ * acesData.values[429].x;

        
        
        
        M_compr=M * acesPow(tonemapped_J / J, acesData.values[64].x);

        
        M_compr=M_compr / Mnorm;

        
        
        
        
        
        M_compr=limit - toe(limit - M_compr, toe_limit, toe_snJ_sat, toe_sqrt_nJ_sat_thr);

        
        
        
        
        M_compr=toe(M_compr, limit, toe_nJ_compr, snJ);

        
        M_compr=M_compr * Mnorm;
    }

    var out:vec3f=vec3f(tonemapped_J, M_compr, h);
    return out;

}
fn tonemap_and_compress_fwd(JMh:vec3f)->vec3f {

    

    
    var linear:f32=J_to_Y(JMh[0], aces_input_params()) / ref_luminance;

    var tonemapped_Y:f32=tonescale_fwd(linear, aces_ts());

    var J_ts:f32=Y_to_J(tonemapped_Y, aces_input_params());

    
    var JMh_tc:vec3f=chroma_compress_fwd(JMh, J_ts);

    return JMh_tc;

}
fn compute_compression_vector_slope(intersect_J:f32,focus_J:f32,limit_J_max:f32,slope_gain:f32)->f32 {

    var direction_scalar:f32;
    if (intersect_J < focus_J)
    {
        direction_scalar=intersect_J;
    }
    else
    {
        direction_scalar=limit_J_max - intersect_J;
    }
    return direction_scalar * (intersect_J - focus_J) / (focus_J * slope_gain);

}
fn smin_scaled(a:f32,b:f32,scale_reference:f32)->f32 {

    var s_scaled:f32=smooth_cusps * scale_reference;
    var h:f32=max(s_scaled - abs(a - b), 0.0) / s_scaled;
    return min(a, b) - h * h * h * s_scaled * (1. / 6.);

}
fn estimate_line_and_boundary_intersection_M(J_axis_intersect:f32,slope:f32,inv_gamma:f32,J_max:f32,M_max:f32,J_intersection_reference:f32)->f32 {

    
    
    
    

    
    
    var normalised_J:f32=J_axis_intersect / J_intersection_reference;
    var shifted_intersection:f32=J_intersection_reference * acesPow(normalised_J, inv_gamma);

    
    
    

    
    return shifted_intersection * M_max / (J_max - slope * M_max);

}
fn find_gamut_boundary_intersection(JM_cusp:vec2f,J_max:f32,gamma_top_inv:f32,gamma_bottom_inv:f32,J_intersect_source:f32,slope:f32,J_intersect_cusp:f32)->f32 {

    var M_boundary_lower:f32=estimate_line_and_boundary_intersection_M(J_intersect_source,
                                                                             slope,
                                                                             gamma_bottom_inv,
                                                                             JM_cusp[0],
                                                                             JM_cusp[1],
                                                                             J_intersect_cusp);

    
    
    var f_J_intersect_cusp:f32=J_max - J_intersect_cusp;
    var f_J_intersect_source:f32=J_max - J_intersect_source;
    var f_JM_cusp_J:f32=J_max - JM_cusp[0];
    var M_boundary_upper:f32=estimate_line_and_boundary_intersection_M(f_J_intersect_source,
                                                                             -slope,
                                                                             gamma_top_inv,
                                                                             f_JM_cusp_J,
                                                                             JM_cusp[1],
                                                                             f_J_intersect_cusp);

    
    var M_boundary:f32=smin_scaled(M_boundary_lower, M_boundary_upper, JM_cusp[1]);
    return M_boundary;

}
fn get_focus_gain(J:f32,analytical_threshold:f32,limit_J_max:f32,focus_dist:f32)->f32 {

    var gain:f32=limit_J_max * focus_dist;

    if (J > analytical_threshold)
    {
        
        var gain_adjustment:f32=acesLog10((limit_J_max - analytical_threshold) / max(0.0001, limit_J_max - J));
        gain_adjustment=gain_adjustment * gain_adjustment + 1.;
        gain=gain * gain_adjustment;
    }

    return gain;

}
fn remap_M(M:f32,gamut_boundary_M:f32,reach_boundary_M:f32)->f32 {

    var boundary_ratio:f32=gamut_boundary_M / reach_boundary_M;
    var proportion:f32=max(boundary_ratio, compression_threshold);
    var threshold:f32=proportion * gamut_boundary_M;

    if (M <= threshold || proportion >= 1.) { return M; }

    
    var m_offset:f32=M - threshold;
    var gamut_offset:f32=gamut_boundary_M - threshold;
    var reach_offset:f32=reach_boundary_M - threshold;

    var scale:f32=reach_offset / ((reach_offset / gamut_offset) - 1.);
    var nd:f32=m_offset / scale;

    
    return threshold + reinhard_remap(scale, nd);

}
fn compress_gamut(JMh:vec3f,Jx:f32,hdp:HueDependentGamutParams)->vec3f {

    var J:f32=JMh[0];
    var M:f32=JMh[1];
    var h:f32=JMh[2];

    var slope_gain:f32=get_focus_gain(Jx, hdp.analytical_threshold, acesData.values[63].x, acesData.values[432].x);
    var J_intersect_source:f32=solve_J_intersect(J, M, hdp.focus_J, acesData.values[63].x, slope_gain);
    var gamut_slope:f32=compute_compression_vector_slope(J_intersect_source, hdp.focus_J, acesData.values[63].x, slope_gain);

    var J_intersect_cusp:f32=solve_J_intersect(hdp.JMcusp[0], hdp.JMcusp[1], hdp.focus_J, acesData.values[63].x, slope_gain);

    var gamut_boundary_M:f32=find_gamut_boundary_intersection(hdp.JMcusp,
                                                                    acesData.values[63].x,
                                                                    hdp.gamma_top_inv,
                                                                    hdp.gamma_bottom_inv,
                                                                    J_intersect_source,
                                                                    gamut_slope,
                                                                    J_intersect_cusp);

    if (gamut_boundary_M <= 0.)
    {
        var returnJMh:vec3f=vec3f(J, 0., h);
        return returnJMh;
    }

    var reach_max_M:f32=reach_M_from_table(h);

    var reach_boundary_M:f32=estimate_line_and_boundary_intersection_M(J_intersect_source,
                                                                             gamut_slope,
                                                                             acesData.values[64].x,
                                                                             acesData.values[63].x,
                                                                             reach_max_M,
                                                                             acesData.values[63].x);

    var remapped_M:f32=remap_M(M, gamut_boundary_M, reach_boundary_M);

    var JMhcompressed:vec3f=vec3f(J_intersect_source + remapped_M * gamut_slope,
                              remapped_M,
                              h);

    return JMhcompressed;

}
fn cusp_from_table(h:f32)->vec2f {

    var lo:vec3f;
    var hi:vec3f;

    var low_i:i32=i32(0);
    var high_i:i32=i32(baseIndex + tableSize);
    var i:i32=i32(hue_position_in_uniform_table(h, tableSize) + baseIndex);

    while (low_i + 1 < high_i)
    {
        if (h > acesData.values[796+i].xyz[2])
        {
            low_i=i32(i);
        }
        else
        {
            high_i=i32(i);
        }
        i=i32((low_i+high_i)/2);
    }
    lo=acesData.values[796+high_i - 1].xyz;
    hi=acesData.values[796+high_i].xyz;

    var t:f32=(h - lo[2]) / (hi[2] - lo[2]);
    var cusp_J:f32=lerp(lo[0], hi[0], t);
    var cusp_M:f32=lerp(lo[1], hi[1], t);

    var cusp_JM:vec2f=vec2f(cusp_J, cusp_M);

    return cusp_JM;

}
fn lookup_hue_interval(h:f32)->i32 {

    
    

    
    var i:i32=i32(baseIndex + hue_position_in_uniform_table(h, totalTableSize));
    var i_lo:i32=i32(max(baseIndex, i + vec2i(acesData.values[1520].xy)[0]));
    var i_hi:i32=i32(min(baseIndex + tableSize, i + vec2i(acesData.values[1520].xy)[1]));

    while (i_lo + 1 < i_hi)
    {
        if (h > acesData.values[434+i].x)
        {
            i_lo=i32(i);
        }
        else
        {
            i_hi=i32(i);
        }
        i=i32((i_lo+i_hi)/2);
    }

    i_hi=i32(max(1, i_hi));

    return i_hi;

}
fn interpolation_weight(h:f32,h_lo:f32,h_hi:f32)->f32 {

    return (h - h_lo);

}
fn compute_focus_J(cusp_J:f32,mid_J:f32,limit_J_max:f32)->f32 {

    return lerp(cusp_J, mid_J, min(1, cusp_mid_blend - (cusp_J / limit_J_max)));

}
fn init_HueDependentGamutParams(hue:f32)->HueDependentGamutParams {

    var hdp:HueDependentGamutParams;
    hdp.gamma_bottom_inv = acesData.values[433].x;

    var i_hi:i32=i32(lookup_hue_interval(hue));
    var t:f32=interpolation_weight(hue, acesData.values[434+i_hi - 1].x, acesData.values[434+i_hi].x);

    hdp.JMcusp = cusp_from_table(hue);
    hdp.gamma_top_inv = lerp(acesData.values[1158+i_hi - 1].x, acesData.values[1158+i_hi].x, t);
    hdp.focus_J = compute_focus_J(hdp.JMcusp[0], acesData.values[431].x, acesData.values[63].x);
    hdp.analytical_threshold = lerp(hdp.JMcusp[0], acesData.values[63].x, focus_gain_blend);

    return hdp;

}
fn gamut_compress_fwd(JMh:vec3f)->vec3f {

    var J:f32=JMh[0];
    var M:f32=JMh[1];
    var h:f32=JMh[2];

    if (J <= 0.0)
    {
        var JMh:vec3f=vec3f(0., 0., h);
        return JMh;
    }

    if (M < 0. || J > acesData.values[63].x)
    {
        var JMh:vec3f=vec3f(J, 0., h);
        return JMh;
    }

    var hdp:HueDependentGamutParams=init_HueDependentGamutParams(h);

    return compress_gamut(JMh, J, hdp);

}
fn outputTransform_fwd(aces:vec3f)->vec3f {

    var AP0_clamped:vec3f=clamp_AP0_to_AP1(aces, 0., aces_ts().forward_limit);

    var JMh:vec3f=RGB_to_JMh(AP0_clamped, aces_input_params());

    var tonemappedJMh:vec3f=tonemap_and_compress_fwd(JMh);

    var compressedJMh:vec3f=gamut_compress_fwd(tonemappedJMh);

    var RGBout:vec3f=JMh_to_RGB(compressedJMh, aces_limit_params());

    return RGBout;

}
// Two-component arithmetic retains the CTL equations at cone-response cancellations.
// This changes evaluation precision, not the reference transform or its parameters.
fn ds(a:f32)->vec2f {return vec2f(a,0.);}
fn dsAdd(a:vec2f,b:vec2f)->vec2f {
  let s=acesSum(a.x,b.x);return acesSum(s.x,s.y+a.y+b.y);
}
fn dsNeg(a:vec2f)->vec2f {return -a;}
fn dsSub(a:vec2f,b:vec2f)->vec2f {return dsAdd(a,-b);}
fn dsMul(a:vec2f,b:vec2f)->vec2f {
  let p=acesRound(a.x*b.x);return acesSum(p,fma(a.x,b.x,-p)+a.x*b.y+a.y*b.x+a.y*b.y);
}
fn dsDiv(a:vec2f,b:vec2f)->vec2f {
  let q=a.x/b.x;let r=dsSub(a,dsMul(ds(q),b));return acesSum(q,(r.x+r.y)/b.x);
}
fn dsValue(a:vec2f)->f32 {return a.x+a.y;}
fn dsSqrt(v:vec2f)->vec2f {
  if(v.x==0.) {return ds(0.);}
  let x=sqrt(v.x);let r=dsSub(v,dsMul(ds(x),ds(x)));
  return acesSum(x,(r.x+r.y)/(2.*x));
}
fn dsLog(a:vec2f)->vec2f {
  let bits=bitcast<u32>(a.x);var exponent=f32(i32((bits>>23u)&255u)-127);
  var mantissa=bitcast<f32>((bits&0x7fffffu)|0x3f800000u);
  if(mantissa>1.4142135623730951){mantissa*=.5;exponent+=1.;}
  let z=dsDiv(ds(mantissa-1.),dsAdd(ds(mantissa),ds(1.)));let z2=dsMul(z,z);
  var polynomial=vec2f(0.058823529411764705,-2.1913472425527658e-10);
  polynomial=dsAdd(vec2f(0.06666666666666667,-3.4769376128229723e-9),dsMul(z2,polynomial));
  polynomial=dsAdd(vec2f(0.07692307692307693,-2.8656079176236915e-9),dsMul(z2,polynomial));
  polynomial=dsAdd(vec2f(0.09090909090909091,-2.7093020327217943e-9),dsMul(z2,polynomial));
  polynomial=dsAdd(vec2f(0.1111111111111111,-8.278422947149977e-10),dsMul(z2,polynomial));
  polynomial=dsAdd(vec2f(0.14285714285714285,-6.3862119481505886e-9),dsMul(z2,polynomial));
  polynomial=dsAdd(vec2f(0.2,-2.980232227667301e-9),dsMul(z2,polynomial));
  polynomial=dsAdd(vec2f(0.3333333333333333,-9.934107481068821e-9),dsMul(z2,polynomial));
  polynomial=dsAdd(vec2f(1,0),dsMul(z2,polynomial));
  let sum=dsMul(z,polynomial);
  let ln2=vec2f(.6931471805599453,-1.904654299957768e-9);
  return dsAdd(dsAdd(dsMul(ds(2.),sum),dsMul(ds(exponent),ln2)),ds(a.y/a.x));
}
fn dsExp(a:vec2f)->vec2f {
  let n=round(a.x/ .6931471805599453);
  let r=dsSub(a,dsMul(ds(n),vec2f(.6931471805599453,-1.904654299957768e-9)));
  var sum=vec2f(1.1470745597729725e-11,2.372207640763624e-19);
  sum=dsAdd(vec2f(1.6059043836821613e-10,-5.352526692508485e-18),dsMul(r,sum));
  sum=dsAdd(vec2f(2.08767569878681e-9,1.1082839478332097e-16),dsMul(r,sum));
  sum=dsAdd(vec2f(2.505210838544172e-8,4.4176231769972645e-16),dsMul(r,sum));
  sum=dsAdd(vec2f(2.755731922398589e-7,-7.575112420809432e-15),dsMul(r,sum));
  sum=dsAdd(vec2f(0.0000027557319223985893,3.7935713937038186e-14),dsMul(r,sum));
  sum=dsAdd(vec2f(0.0000248015873015873,-3.406996025904184e-13),dsMul(r,sum));
  sum=dsAdd(vec2f(0.0001984126984126984,-2.725596820723347e-12),dsMul(r,sum));
  sum=dsAdd(vec2f(0.001388888888888889,-3.3631092919220174e-11),dsMul(r,sum));
  sum=dsAdd(vec2f(0.008333333333333333,-4.3461720160287154e-10),dsMul(r,sum));
  sum=dsAdd(vec2f(0.041666666666666664,-1.2417634351336027e-9),dsMul(r,sum));
  sum=dsAdd(vec2f(0.16666666666666666,-4.967053740534411e-9),dsMul(r,sum));
  sum=dsAdd(vec2f(0.5,0),dsMul(r,sum));
  sum=dsAdd(vec2f(1,0),dsMul(r,sum));
  sum=dsAdd(vec2f(1,0),dsMul(r,sum));
  return dsMul(sum,ds(exp2(n)));
}
fn dsPow(a:vec2f,b:vec2f)->vec2f {
  if(a.x==0.) {return ds(0.);}
  return dsExp(dsMul(dsLog(a),b));
}
fn dsCone(v:vec2f)->vec2f {
  let power=dsPow(v*sign(v.x),vec2f(.42,1.3113021835042815e-8));
  return dsDiv(power,dsAdd(vec2f(27.13,8.392333992190082e-7),power))*sign(v.x);
}
fn dsConeInverse(v:vec2f)->vec2f {
  let a=select(v*sign(v.x),ds(.99),abs(v.x)>.99);
  let base=dsDiv(dsMul(vec2f(27.13,8.392333992190082e-7),a),dsSub(ds(1.),a));
  return dsPow(base,vec2f(2.380952380952381,2.2706531321858847e-8))*sign(v.x);
}
fn dsMatrix(v:array<vec2f,3>,hi:mat3x3f,lo:mat3x3f)->array<vec2f,3> {
  var result:array<vec2f,3>;
  for(var c=0;c<3;c++) {
    result[c]=dsAdd(dsAdd(dsMul(v[0],vec2f(hi[0][c],lo[0][c])),dsMul(v[1],vec2f(hi[1][c],lo[1][c]))),dsMul(v[2],vec2f(hi[2][c],lo[2][c])));
  }
  return result;
}
fn RGB_to_Aab(RGB:vec3f,p:JMhParams)->vec3f {
  let cone=dsMatrix(array<vec2f,3>(ds(RGB.x),ds(RGB.y),ds(RGB.z)),p.MATRIX_RGB_to_CAM16_c,p.MATRIX_RGB_to_CAM16_c_lo);
  let response=dsMatrix(array<vec2f,3>(dsCone(cone[0]),dsCone(cone[1]),dsCone(cone[2])),p.MATRIX_cone_response_to_Aab,p.MATRIX_cone_response_to_Aab_lo);
  return vec3f(dsValue(response[0]),dsValue(response[1]),dsValue(response[2]));
}
fn Aab_to_RGB(Aab:vec3f,p:JMhParams)->vec3f {
  let cone=dsMatrix(array<vec2f,3>(ds(Aab.x),ds(Aab.y),ds(Aab.z)),p.MATRIX_Aab_to_cone_response,p.MATRIX_Aab_to_cone_response_lo);
  let response=dsMatrix(array<vec2f,3>(dsConeInverse(cone[0]),dsConeInverse(cone[1]),dsConeInverse(cone[2])),p.MATRIX_CAM16_c_to_RGB,p.MATRIX_CAM16_c_to_RGB_lo);
  return vec3f(dsValue(response[0]),dsValue(response[1]),dsValue(response[2]));
}

fn acesPow(a:f32,b:f32)->f32 {return pow(a,b);}
fn J_to_Y(J:f32,p:JMhParams)->f32 {
  let a=dsPow(dsDiv(ds(abs(J)),ds(100.)),vec2f(p.inv_cz,p.inv_cz_lo));
  return dsValue(dsDiv(dsConeInverse(dsMul(a,vec2f(p.A_w_J,p.A_w_J_lo))),vec2f(p.F_L_n,p.F_L_n_lo)));
}
fn Y_to_J(Y:f32,p:JMhParams)->f32 {
  let cone=dsCone(dsMul(ds(abs(Y)),vec2f(p.F_L_n,p.F_L_n_lo)));
  let a=dsMul(cone,vec2f(p.inv_A_w_J,p.inv_A_w_J_lo));
  return sign(Y)*dsValue(dsMul(ds(100.),dsPow(a,vec2f(p.cz,p.cz_lo))));
}
// Retain the quadratic discriminant and denominator at the gamut intersection.
fn solve_J_intersect(J:f32,M:f32,focusJ:f32,maxJ:f32,slope_gain:f32)->f32 {
  let scaled=dsDiv(ds(M),ds(slope_gain));let a=dsDiv(scaled,ds(focusJ));
  var b:vec2f;var c:vec2f;
  if(J<focusJ) {b=dsSub(ds(1.),scaled);c=ds(-J);}
  else {b=dsNeg(dsAdd(dsAdd(ds(1.),scaled),dsMul(ds(maxJ),a)));c=dsAdd(dsMul(ds(maxJ),scaled),ds(J));}
  let root=dsSqrt(dsSub(dsMul(b,b),dsMul(ds(4.),dsMul(a,c))));
  let denominator=select(dsSub(b,root),dsAdd(b,root),J<focusJ);
  return dsValue(dsDiv(dsMul(ds(-2.),c),denominator));
}
fn Aab_to_JMh(Aab:vec3f,p:JMhParams)->vec3f {
  if(Aab.x<=0.) {return vec3f(0.);}
  let J=dsValue(dsMul(ds(100.),dsPow(ds(Aab.x),vec2f(p.cz,p.cz_lo))));
  return vec3f(J,length(Aab.yz),wrap_to_360(radians_to_degrees(atan2(Aab.z,Aab.y))));
}
fn JMh_to_Aab(JMh:vec3f,p:JMhParams)->vec3f {
  let a=dsValue(dsPow(dsDiv(ds(JMh.x),ds(100.)),vec2f(p.inv_cz,p.inv_cz_lo)));
  // Retain the degrees-to-radians residual before trigonometry near gamut boundaries.
  let h=dsMul(ds(JMh.z),vec2f(.017453292519943295,1.3519960498364902e-10));
  let co=fma(-sin(h.x),h.y,cos(h.x));
  let si=fma(cos(h.x),h.y,sin(h.x));
  return vec3f(a,JMh.y*co,JMh.y*si);
}
`
