// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the ACES Project.
// Generated by scripts/generate-aces.py from pinned CTL; do not edit.
// CTL declarations/initialization are retained for auditable correspondence.
/* eslint-disable prefer-const, no-useless-assignment */

export interface Chromaticities {
  red: number[]
  green: number[]
  blue: number[]
  white: number[]
}
const M_PI = Math.PI
const roundCtl = (x: number) => Math.trunc(x + (x < 0 ? -0.5 : 0.5))
const fmod = (x: number, y: number) => x % y
// CTL copysign uses sign(0)=0, unlike C's copysign.
const copysign = (x: number, y: number) => Math.sign(y) * Math.abs(x)
// Scratch vectors are leased only for a synchronous pixel evaluation; prepared tables own arrays.
const scratch = Array.from({ length: 256 }, () => [0, 0, 0])
let scratchCursor = -1
export function beginAcesPixel() {
  scratchCursor = 0
}
export function endAcesPixel() {
  scratchCursor = -1
}
function acesVec(a: number, b: number, c: number): number[] {
  if (scratchCursor < 0) return [a, b, c]
  const v = scratch[scratchCursor++]
  if (!v) throw new Error('ACES scratch bound exceeded.')
  v[0] = a
  v[1] = b
  v[2] = c
  return v
}
const acesCopy = (v: number[]) => acesVec(v[0], v[1], v[2])
const mult_f3_f33 = (v: number[], m: number[][]) =>
  acesVec(
    v[0] * m[0][0] + v[1] * m[1][0] + v[2] * m[2][0],
    v[0] * m[0][1] + v[1] * m[1][1] + v[2] * m[2][1],
    v[0] * m[0][2] + v[1] * m[1][2] + v[2] * m[2][2],
  )
const mult_f_f3 = (s: number, v: number[]) => acesVec(s * v[0], s * v[1], s * v[2])
const mult_f_f33 = (s: number, m: number[][]) => m.map((r) => r.map((x) => s * x))
const mult_f33_f33 = (a: number[][], b: number[][]) => a.map((r) => mult_f3_f33(r, b))
function invert_f33(m: number[][]): number[][] {
  const [a, b, c] = m
  const det =
    a[0] * (b[1] * c[2] - b[2] * c[1]) -
    a[1] * (b[0] * c[2] - b[2] * c[0]) +
    a[2] * (b[0] * c[1] - b[1] * c[0])
  return [
    [b[1] * c[2] - b[2] * c[1], a[2] * c[1] - a[1] * c[2], a[1] * b[2] - a[2] * b[1]],
    [b[2] * c[0] - b[0] * c[2], a[0] * c[2] - a[2] * c[0], a[2] * b[0] - a[0] * b[2]],
    [b[0] * c[1] - b[1] * c[0], a[1] * c[0] - a[0] * c[1], a[0] * b[1] - a[1] * b[0]],
  ].map((r) => r.map((x) => x / det))
}
export interface TSParams {
  n: number
  n_r: number
  g: number
  t_1: number
  c_t: number
  s_2: number
  u_2: number
  m_2: number
  forward_limit: number
  inverse_limit: number
  log_peak: number
}
function newTSParams(): TSParams {
  return {
    n: 0,
    n_r: 0,
    g: 0,
    t_1: 0,
    c_t: 0,
    s_2: 0,
    u_2: 0,
    m_2: 0,
    forward_limit: 0,
    inverse_limit: 0,
    log_peak: 0,
  }
}
export interface JMhParams {
  MATRIX_RGB_to_CAM16_c: number[][]
  MATRIX_CAM16_c_to_RGB: number[][]
  MATRIX_cone_response_to_Aab: number[][]
  MATRIX_Aab_to_cone_response: number[][]
  F_L_n: number
  cz: number
  inv_cz: number
  A_w_J: number
  inv_A_w_J: number
}
function newJMhParams(): JMhParams {
  return {
    MATRIX_RGB_to_CAM16_c: Array.from({ length: 3 }, () => Array.from({ length: 3 }, () => 0)),
    MATRIX_CAM16_c_to_RGB: Array.from({ length: 3 }, () => Array.from({ length: 3 }, () => 0)),
    MATRIX_cone_response_to_Aab: Array.from({ length: 3 }, () =>
      Array.from({ length: 3 }, () => 0),
    ),
    MATRIX_Aab_to_cone_response: Array.from({ length: 3 }, () =>
      Array.from({ length: 3 }, () => 0),
    ),
    F_L_n: 0,
    cz: 0,
    inv_cz: 0,
    A_w_J: 0,
    inv_A_w_J: 0,
  }
}
export interface HueDependentGamutParams {
  JMcusp: number[]
  gamma_bottom_inv: number
  gamma_top_inv: number
  focus_J: number
  analytical_threshold: number
}
function newHueDependentGamutParams(): HueDependentGamutParams {
  return {
    JMcusp: Array.from({ length: 2 }, () => 0),
    gamma_bottom_inv: 0,
    gamma_top_inv: 0,
    focus_J: 0,
    analytical_threshold: 0,
  }
}
export interface ODTParams {
  peakLuminance: number
  input_params: JMhParams
  reach_params: JMhParams
  limit_params: JMhParams
  ts: TSParams
  limit_J_max: number
  model_gamma_inv: number
  TABLE_reach_M: number[]
  sat: number
  sat_thr: number
  compr: number
  chroma_compress_scale: number
  mid_J: number
  focus_dist: number
  lower_hull_gamma_inv: number
  TABLE_hues: number[]
  TABLE_gamut_cusps: number[][]
  TABLE_upper_hull_gamma: number[]
  hue_linearity_search_range: number[]
}
function newODTParams(): ODTParams {
  return {
    peakLuminance: 0,
    input_params: newJMhParams(),
    reach_params: newJMhParams(),
    limit_params: newJMhParams(),
    ts: newTSParams(),
    limit_J_max: 0,
    model_gamma_inv: 0,
    TABLE_reach_M: Array.from({ length: totalTableSize }, () => 0),
    sat: 0,
    sat_thr: 0,
    compr: 0,
    chroma_compress_scale: 0,
    mid_J: 0,
    focus_dist: 0,
    lower_hull_gamma_inv: 0,
    TABLE_hues: Array.from({ length: totalTableSize }, () => 0),
    TABLE_gamut_cusps: Array.from({ length: totalTableSize }, () =>
      Array.from({ length: 3 }, () => 0),
    ),
    TABLE_upper_hull_gamma: Array.from({ length: totalTableSize }, () => 0),
    hue_linearity_search_range: Array.from({ length: 2 }, () => 0),
  }
}
export const AP0: Chromaticities = {
  red: [0.7347, 0.2653],
  green: [0.0, 1.0],
  blue: [0.0001, -0.077],
  white: [0.32168, 0.33767],
}
export const AP0_XYZ_TO_RGB: number[][] = XYZtoRGB_f33(AP0, 1.0).map((r) => r.slice())
export const AP0_RGB_TO_XYZ: number[][] = RGBtoXYZ_f33(AP0, 1.0).map((r) => r.slice())
export const AP1: Chromaticities = {
  red: [0.713, 0.293],
  green: [0.165, 0.83],
  blue: [0.128, 0.044],
  white: [0.32168, 0.33767],
}
export const AP1_XYZ_TO_RGB: number[][] = XYZtoRGB_f33(AP1, 1.0).map((r) => r.slice())
export const AP1_RGB_TO_XYZ: number[][] = RGBtoXYZ_f33(AP1, 1.0).map((r) => r.slice())
export const AP0_TO_AP1: number[][] = mult_f33_f33(AP0_RGB_TO_XYZ, AP1_XYZ_TO_RGB).map((r) =>
  r.slice(),
)
export const AP1_TO_AP0: number[][] = mult_f33_f33(AP1_RGB_TO_XYZ, AP0_XYZ_TO_RGB).map((r) =>
  r.slice(),
)
export const REACH_PRI: Chromaticities = AP1
export const tableSize: number = Math.trunc(360)
export const additionalTableEntries: number = Math.trunc(2)
export const totalTableSize: number = Math.trunc(tableSize + additionalTableEntries)
export const baseIndex: number = Math.trunc(1)
export const hue_limit: number = 360
export const cuspCornerCount: number = Math.trunc(6)
export const totalCornerCount: number = Math.trunc(cuspCornerCount + 2)
export const max_sorted_corners: number = Math.trunc(2 * cuspCornerCount)
export const reach_cusp_tolerance: number = 1e-3
export const display_cusp_tolerance: number = 1e-7
export const gamma_minimum: number = 0.0
export const gamma_maximum: number = 5.0
export const gamma_search_step: number = 0.4
export const gamma_accuracy: number = 1e-5
export const ref_luminance: number = 100
export const L_A: number = 100
export const Y_b: number = 20
export const surround: number[] = [0.9, 0.59, 0.9]
export const J_scale: number = 100.0
export const cam_nl_Y_reference: number = 100.0
export const cam_nl_offset: number = 0.2713 * cam_nl_Y_reference
export const cam_nl_scale: number = 4.0 * cam_nl_Y_reference
export const model_gamma: number = surround[1] * (1.48 + Math.sqrt(Y_b / ref_luminance))
export const chroma_compress: number = 2.4
export const chroma_compress_fact: number = 3.3
export const chroma_expand: number = 1.3
export const chroma_expand_fact: number = 0.69
export const chroma_expand_thr: number = 0.5
export const smooth_cusps: number = 0.12
export const smooth_m: number = 0.27
export const cusp_mid_blend: number = 1.3
export const focus_gain_blend: number = 0.3
export const focus_adjust_gain: number = 0.55
export const focus_distance: number = 1.35
export const focus_distance_scaling: number = 1.75
export const compression_threshold: number = 0.75
export const MATRIX_IDENTITY: number[][] = [
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
]
export const test_count: number = Math.trunc(5)
export const testPositions: number[] = [0.01, 0.1, 0.5, 0.8, 0.99]
export function init_TSParams(peakLuminance: number): TSParams {
  const n: number = peakLuminance

  const n_r: number = 100.0
  const g: number = 1.15
  const c: number = 0.18
  const c_d: number = 10.013
  const w_g: number = 0.14
  const t_1: number = 0.04
  const r_hit_min: number = 128
  const r_hit_max: number = 896

  const r_hit: number =
    r_hit_min + (r_hit_max - r_hit_min) * (Math.log(n / n_r) / Math.log(10000 / 100))
  const m_0: number = n / n_r
  const m_1: number = 0.5 * (m_0 + Math.sqrt(m_0 * (m_0 + 4 * t_1)))
  const u: number = Math.pow(r_hit / m_1 / (r_hit / m_1 + 1), g)
  const m: number = m_1 / u
  const w_i: number = Math.log(n / 100) / Math.log(2)
  const c_t: number = (c_d / n_r) * (1 + w_i * w_g)
  const g_ip: number = 0.5 * (c_t + Math.sqrt(c_t * (c_t + 4 * t_1)))
  const g_ipp2: number = -(m_1 * Math.pow(g_ip / m, 1 / g)) / (Math.pow(g_ip / m, 1 / g) - 1)
  const w_2: number = c / g_ipp2
  const s_2: number = w_2 * m_1
  const u_2: number = Math.pow(r_hit / m_1 / (r_hit / m_1 + w_2), g)
  const m_2: number = m_1 / u_2

  let p: TSParams = newTSParams()
  p.n = n
  p.n_r = n_r
  p.g = g
  p.t_1 = t_1
  p.c_t = c_t
  p.s_2 = s_2
  p.u_2 = u_2
  p.m_2 = m_2
  p.forward_limit = 8.0 * r_hit
  p.inverse_limit = n / (u_2 * n_r)
  p.log_peak = Math.log10(n / n_r)

  return p
}
export function tonescale_fwd(x: number, params: TSParams): number {
  let f: number = params.m_2 * Math.pow(Math.max(0.0, x) / (x + params.s_2), params.g)
  let h: number = Math.max(0, (f * f) / (f + params.t_1))

  return h * params.n_r
}
export function wrap_to_360(hue: number): number {
  let y: number = fmod(hue, 360)
  if (y < 0) {
    y = y + 360
  }
  return y
}
export function hue_position_in_uniform_table(hue: number, table_size: number): number {
  const wrapped_hue: number = wrap_to_360(hue)
  let result: number = Math.trunc((wrapped_hue / hue_limit) * table_size)
  return result
}
export function base_hue_for_position(i_lo: number, table_size: number): number {
  let result: number = (i_lo * hue_limit) / table_size
  return result
}
export function _post_adaptation_cone_response_compression_fwd(Rc: number): number {
  const F_L_Y: number = Math.pow(Rc, 0.42)
  const Ra: number = F_L_Y / (cam_nl_offset + F_L_Y)
  return Ra
}
export function _post_adaptation_cone_response_compression_inv(Ra: number): number {
  const Ra_lim: number = Math.min(Ra, 0.99)
  const F_L_Y: number = (cam_nl_offset * Ra_lim) / (1 - Ra_lim)
  const Rc: number = Math.pow(F_L_Y, 1 / 0.42)
  return Rc
}
export function post_adaptation_cone_response_compression_fwd(v: number): number {
  const abs_v: number = Math.abs(v)
  const Ra: number = _post_adaptation_cone_response_compression_fwd(abs_v)
  return copysign(Ra, v)
}
export function post_adaptation_cone_response_compression_inv(v: number): number {
  const abs_v: number = Math.abs(v)
  const Rc: number = _post_adaptation_cone_response_compression_inv(abs_v)
  return copysign(Rc, v)
}
export function Achromatic_n_to_J(A: number, cz: number): number {
  return J_scale * Math.pow(A, cz)
}
export function J_to_Achromatic_n(J: number, inv_cz: number): number {
  return Math.pow(J * (1 / J_scale), inv_cz)
}
export function _A_to_Y(A: number, p: JMhParams): number {
  let Ra: number = p.A_w_J * A
  let Y: number = _post_adaptation_cone_response_compression_inv(Ra) / p.F_L_n

  return Y
}
export function J_to_Y(J: number, p: JMhParams): number {
  let abs_J: number = Math.abs(J)

  return _A_to_Y(J_to_Achromatic_n(abs_J, p.inv_cz), p)
}
export function Y_to_J(Y: number, p: JMhParams): number {
  let abs_Y: number = Math.abs(Y)
  let Ra: number = _post_adaptation_cone_response_compression_fwd(abs_Y * p.F_L_n)
  let J: number = Achromatic_n_to_J(Ra * p.inv_A_w_J, p.cz)

  return copysign(J, Y)
}
export function RGB_to_Aab(RGB: number[], p: JMhParams): number[] {
  let rgb_m: number[] = acesCopy(mult_f3_f33(RGB, p.MATRIX_RGB_to_CAM16_c))

  let rgb_a: number[] = acesVec(
    post_adaptation_cone_response_compression_fwd(rgb_m[0]),
    post_adaptation_cone_response_compression_fwd(rgb_m[1]),
    post_adaptation_cone_response_compression_fwd(rgb_m[2]),
  )

  let Aab: number[] = acesCopy(mult_f3_f33(rgb_a, p.MATRIX_cone_response_to_Aab))

  return Aab
}
export function Aab_to_JMh(Aab: number[], p: JMhParams): number[] {
  let JMh: number[] = acesVec(0, 0, 0)
  if (Aab[0] <= 0) {
    return JMh
  }
  let J: number = Achromatic_n_to_J(Aab[0], p.cz)
  let M: number = Math.sqrt(Aab[1] * Aab[1] + Aab[2] * Aab[2])
  let h_rad: number = Math.atan2(Aab[2], Aab[1])
  let h: number = wrap_to_360(radians_to_degrees(h_rad))

  JMh[0] = J
  JMh[1] = M
  JMh[2] = h

  return JMh
}
export function RGB_to_JMh(RGB: number[], p: JMhParams): number[] {
  let Aab: number[] = acesCopy(RGB_to_Aab(RGB, p))
  let JMh: number[] = acesCopy(Aab_to_JMh(Aab, p))

  return JMh
}
export function JMh_to_Aab(JMh: number[], p: JMhParams): number[] {
  let J: number = JMh[0]
  let M: number = JMh[1]
  let h: number = JMh[2]
  let h_rad: number = degrees_to_radians(h)
  let cos_hr: number = Math.cos(h_rad)
  let sin_hr: number = Math.sin(h_rad)

  let A: number = J_to_Achromatic_n(J, p.inv_cz)
  let a: number = M * cos_hr
  let b: number = M * sin_hr
  let Aab: number[] = acesVec(A, a, b)

  return Aab
}
export function Aab_to_RGB(Aab: number[], p: JMhParams): number[] {
  let rgb_a: number[] = acesCopy(mult_f3_f33(Aab, p.MATRIX_Aab_to_cone_response))

  let rgb_m: number[] = acesVec(
    post_adaptation_cone_response_compression_inv(rgb_a[0]),
    post_adaptation_cone_response_compression_inv(rgb_a[1]),
    post_adaptation_cone_response_compression_inv(rgb_a[2]),
  )

  let rgb: number[] = acesCopy(mult_f3_f33(rgb_m, p.MATRIX_CAM16_c_to_RGB))

  return rgb
}
export function JMh_to_RGB(JMh: number[], p: JMhParams): number[] {
  let Aab: number[] = acesCopy(JMh_to_Aab(JMh, p))
  let rgb: number[] = acesCopy(Aab_to_RGB(Aab, p))
  return rgb
}
export function clamp_AP0_to_AP1(
  aces: number[],
  clamp_lower_limit: number,
  clamp_upper_limit: number,
): number[] {
  let AP1: number[] = acesCopy(mult_f3_f33(aces, AP0_TO_AP1))
  let AP1_clamped: number[] = acesCopy(clamp_f3(AP1, clamp_lower_limit, clamp_upper_limit))
  let AP0_clamped: number[] = acesCopy(mult_f3_f33(AP1_clamped, AP1_TO_AP0))

  return AP0_clamped
}
export function reach_M_from_table(h: number, table: number[]): number {
  let base: number = Math.trunc(hue_position_in_uniform_table(h, tableSize))
  let t: number = h - base
  let i_lo: number = Math.trunc(base + baseIndex)
  let i_hi: number = Math.trunc(i_lo + 1)

  return lerp(table[i_lo], table[i_hi], t)
}
export function reinhard_remap(scale: number, nd: number, invert: boolean = false): number {
  if (invert) {
    if (nd >= 1.0) {
      return scale
    } else {
      return scale * -(nd / (nd - 1))
    }
  }
  return (scale * nd) / (1 + nd)
}
export function midpoint(low: number, high: number): number {
  return (low + high) / 2
}
export function toe(
  x: number,
  limit: number,
  k1_in: number,
  k2_in: number,
  invert: boolean = false,
): number {
  if (x > limit) return x

  let k2: number = Math.max(k2_in, 0.001)
  let k1: number = Math.sqrt(k1_in * k1_in + k2 * k2)
  let k3: number = (limit + k1) / (limit + k2)

  if (invert) {
    return (x * x + k1 * x) / (k3 * (x + k2))
  } else {
    const minus_b: number = k3 * x - k1
    const minus_c: number = k2 * k3 * x
    return 0.5 * (minus_b + Math.sqrt(minus_b * minus_b + 4 * minus_c))
  }
}
export function chroma_compress_norm(h: number, chroma_compress_scale: number): number {
  let hr: number = degrees_to_radians(h)

  let a: number = Math.cos(hr)
  let b: number = Math.sin(hr)
  let cos_hr2: number = a * a - b * b
  let sin_hr2: number = 2.0 * a * b
  let cos_hr3: number = 4.0 * a * a * a - 3.0 * a
  let sin_hr3: number = 3.0 * b - 4.0 * b * b * b

  let M: number =
    11.34072 * a +
    16.46899 * cos_hr2 +
    7.8838 * cos_hr3 +
    14.66441 * b +
    -6.37224 * sin_hr2 +
    9.19364 * sin_hr3 +
    77.12896

  return M * chroma_compress_scale
}
export function chroma_compress_fwd(
  JMh: number[],
  tonemapped_J: number,
  p: ODTParams,
  _invert: boolean = false,
): number[] {
  void _invert

  let J: number = JMh[0]
  let M: number = JMh[1]
  let h: number = JMh[2]

  let M_compr: number = M

  if (M != 0.0) {
    const nJ: number = tonemapped_J / p.limit_J_max
    const snJ: number = Math.max(0, 1 - nJ)
    let Mnorm: number = chroma_compress_norm(h, p.chroma_compress_scale)
    let limit: number =
      (Math.pow(nJ, p.model_gamma_inv) * reach_M_from_table(h, p.TABLE_reach_M)) / Mnorm

    let toe_limit: number = limit - 0.001
    let toe_snJ_sat: number = snJ * p.sat
    let toe_sqrt_nJ_sat_thr: number = Math.sqrt(nJ * nJ + p.sat_thr)
    let toe_nJ_compr: number = nJ * p.compr

    M_compr = M * Math.pow(tonemapped_J / J, p.model_gamma_inv)

    M_compr = M_compr / Mnorm

    M_compr = limit - toe(limit - M_compr, toe_limit, toe_snJ_sat, toe_sqrt_nJ_sat_thr, false)

    M_compr = toe(M_compr, limit, toe_nJ_compr, snJ, false)

    M_compr = M_compr * Mnorm
  }

  let out: number[] = acesVec(tonemapped_J, M_compr, h)
  return out
}
export function tonemap_and_compress_fwd(JMh: number[], p: ODTParams): number[] {
  let linear: number = J_to_Y(JMh[0], p.input_params) / ref_luminance

  let tonemapped_Y: number = tonescale_fwd(linear, p.ts)

  let J_ts: number = Y_to_J(tonemapped_Y, p.input_params)

  let JMh_tc: number[] = acesCopy(chroma_compress_fwd(JMh, J_ts, p, false))

  return JMh_tc
}
export function compute_compression_vector_slope(
  intersect_J: number,
  focus_J: number,
  limit_J_max: number,
  slope_gain: number,
): number {
  let direction_scalar: number = 0
  if (intersect_J < focus_J) {
    direction_scalar = intersect_J
  } else {
    direction_scalar = limit_J_max - intersect_J
  }
  return (direction_scalar * (intersect_J - focus_J)) / (focus_J * slope_gain)
}
export function solve_J_intersect(
  J: number,
  M: number,
  focusJ: number,
  maxJ: number,
  slope_gain: number,
): number {
  const M_scaled: number = M / slope_gain
  const a: number = M_scaled / focusJ

  if (J < focusJ) {
    const b: number = 1 - M_scaled
    const c: number = -J
    const det: number = b * b - 4 * a * c
    const root: number = Math.sqrt(det)
    return (-2 * c) / (b + root)
  } else {
    const b: number = -(1 + M_scaled + maxJ * a)
    const c: number = maxJ * M_scaled + J
    const det: number = b * b - 4 * a * c
    const root: number = Math.sqrt(det)
    return (-2 * c) / (b - root)
  }
}
export function smin_scaled(a: number, b: number, scale_reference: number): number {
  const s_scaled: number = smooth_cusps * scale_reference
  const h: number = Math.max(s_scaled - Math.abs(a - b), 0.0) / s_scaled
  return Math.min(a, b) - h * h * h * s_scaled * (1 / 6)
}
export function estimate_line_and_boundary_intersection_M(
  J_axis_intersect: number,
  slope: number,
  inv_gamma: number,
  J_max: number,
  M_max: number,
  J_intersection_reference: number,
): number {
  const normalised_J: number = J_axis_intersect / J_intersection_reference
  const shifted_intersection: number = J_intersection_reference * Math.pow(normalised_J, inv_gamma)

  return (shifted_intersection * M_max) / (J_max - slope * M_max)
}
export function find_gamut_boundary_intersection(
  JM_cusp: number[],
  J_max: number,
  gamma_top_inv: number,
  gamma_bottom_inv: number,
  J_intersect_source: number,
  slope: number,
  J_intersect_cusp: number,
): number {
  const M_boundary_lower: number = estimate_line_and_boundary_intersection_M(
    J_intersect_source,
    slope,
    gamma_bottom_inv,
    JM_cusp[0],
    JM_cusp[1],
    J_intersect_cusp,
  )

  const f_J_intersect_cusp: number = J_max - J_intersect_cusp
  const f_J_intersect_source: number = J_max - J_intersect_source
  const f_JM_cusp_J: number = J_max - JM_cusp[0]
  const M_boundary_upper: number = estimate_line_and_boundary_intersection_M(
    f_J_intersect_source,
    -slope,
    gamma_top_inv,
    f_JM_cusp_J,
    JM_cusp[1],
    f_J_intersect_cusp,
  )

  let M_boundary: number = smin_scaled(M_boundary_lower, M_boundary_upper, JM_cusp[1])
  return M_boundary
}
export function get_focus_gain(
  J: number,
  analytical_threshold: number,
  limit_J_max: number,
  focus_dist: number,
): number {
  let gain: number = limit_J_max * focus_dist

  if (J > analytical_threshold) {
    let gain_adjustment: number = Math.log10(
      (limit_J_max - analytical_threshold) / Math.max(0.0001, limit_J_max - J),
    )
    gain_adjustment = gain_adjustment * gain_adjustment + 1
    gain = gain * gain_adjustment
  }

  return gain
}
export function remap_M(
  M: number,
  gamut_boundary_M: number,
  reach_boundary_M: number,
  invert: boolean = false,
): number {
  const boundary_ratio: number = gamut_boundary_M / reach_boundary_M
  const proportion: number = Math.max(boundary_ratio, compression_threshold)
  const threshold: number = proportion * gamut_boundary_M

  if (M <= threshold || proportion >= 1) return M

  const m_offset: number = M - threshold
  const gamut_offset: number = gamut_boundary_M - threshold
  const reach_offset: number = reach_boundary_M - threshold

  const scale: number = reach_offset / (reach_offset / gamut_offset - 1)
  const nd: number = m_offset / scale

  return threshold + reinhard_remap(scale, nd, invert)
}
export function compress_gamut(
  JMh: number[],
  Jx: number,
  p: ODTParams,
  hdp: HueDependentGamutParams,
  invert: boolean = false,
): number[] {
  const J: number = JMh[0]
  const M: number = JMh[1]
  const h: number = JMh[2]

  const slope_gain: number = get_focus_gain(
    Jx,
    hdp.analytical_threshold,
    p.limit_J_max,
    p.focus_dist,
  )
  const J_intersect_source: number = solve_J_intersect(J, M, hdp.focus_J, p.limit_J_max, slope_gain)
  const gamut_slope: number = compute_compression_vector_slope(
    J_intersect_source,
    hdp.focus_J,
    p.limit_J_max,
    slope_gain,
  )

  const J_intersect_cusp: number = solve_J_intersect(
    hdp.JMcusp[0],
    hdp.JMcusp[1],
    hdp.focus_J,
    p.limit_J_max,
    slope_gain,
  )

  const gamut_boundary_M: number = find_gamut_boundary_intersection(
    hdp.JMcusp,
    p.limit_J_max,
    hdp.gamma_top_inv,
    hdp.gamma_bottom_inv,
    J_intersect_source,
    gamut_slope,
    J_intersect_cusp,
  )

  if (gamut_boundary_M <= 0) {
    let returnJMh: number[] = acesVec(J, 0, h)
    return returnJMh
  }

  let reach_max_M: number = reach_M_from_table(h, p.TABLE_reach_M)

  const reach_boundary_M: number = estimate_line_and_boundary_intersection_M(
    J_intersect_source,
    gamut_slope,
    p.model_gamma_inv,
    p.limit_J_max,
    reach_max_M,
    p.limit_J_max,
  )

  const remapped_M: number = remap_M(M, gamut_boundary_M, reach_boundary_M, invert)

  let JMhcompressed: number[] = acesVec(
    J_intersect_source + remapped_M * gamut_slope,
    remapped_M,
    h,
  )

  return JMhcompressed
}
export function cusp_from_table(h: number, table: number[][]): number[] {
  let lo: number[] = acesVec(0, 0, 0)
  let hi: number[] = acesVec(0, 0, 0)

  let low_i: number = Math.trunc(0)
  let high_i: number = Math.trunc(baseIndex + tableSize)
  let i: number = Math.trunc(hue_position_in_uniform_table(h, tableSize) + baseIndex)

  while (low_i + 1 < high_i) {
    if (h > table[i][2]) {
      low_i = Math.trunc(i)
    } else {
      high_i = Math.trunc(i)
    }
    i = Math.trunc(midpoint(low_i, high_i))
  }
  lo = acesCopy(table[high_i - 1])
  hi = acesCopy(table[high_i])

  let t: number = (h - lo[2]) / (hi[2] - lo[2])
  let cusp_J: number = lerp(lo[0], hi[0], t)
  let cusp_M: number = lerp(lo[1], hi[1], t)

  let cusp_JM: number[] = [cusp_J, cusp_M]

  return cusp_JM
}
export function lookup_hue_interval(
  h: number,
  hue_table: number[],
  hue_linearity_search_range: number[],
): number {
  let i: number = Math.trunc(baseIndex + hue_position_in_uniform_table(h, totalTableSize))
  let i_lo: number = Math.trunc(Math.max(baseIndex, i + hue_linearity_search_range[0]))
  let i_hi: number = Math.trunc(Math.min(baseIndex + tableSize, i + hue_linearity_search_range[1]))

  while (i_lo + 1 < i_hi) {
    if (h > hue_table[i]) {
      i_lo = Math.trunc(i)
    } else {
      i_hi = Math.trunc(i)
    }
    i = Math.trunc(midpoint(i_lo, i_hi))
  }

  i_hi = Math.trunc(Math.max(1, i_hi))

  return i_hi
}
export function interpolation_weight(h: number, h_lo: number, _h_hi: number): number {
  void _h_hi

  return h - h_lo
}
export function compute_focus_J(cusp_J: number, mid_J: number, limit_J_max: number): number {
  return lerp(cusp_J, mid_J, Math.min(1, cusp_mid_blend - cusp_J / limit_J_max))
}
export function init_HueDependentGamutParams(hue: number, p: ODTParams): HueDependentGamutParams {
  let hdp: HueDependentGamutParams = newHueDependentGamutParams()
  hdp.gamma_bottom_inv = p.lower_hull_gamma_inv

  const i_hi: number = Math.trunc(
    lookup_hue_interval(hue, p.TABLE_hues, p.hue_linearity_search_range),
  )
  const t: number = interpolation_weight(hue, p.TABLE_hues[i_hi - 1], p.TABLE_hues[i_hi])

  hdp.JMcusp = acesCopy(cusp_from_table(hue, p.TABLE_gamut_cusps))
  hdp.gamma_top_inv = lerp(p.TABLE_upper_hull_gamma[i_hi - 1], p.TABLE_upper_hull_gamma[i_hi], t)
  hdp.focus_J = compute_focus_J(hdp.JMcusp[0], p.mid_J, p.limit_J_max)
  hdp.analytical_threshold = lerp(hdp.JMcusp[0], p.limit_J_max, focus_gain_blend)

  return hdp
}
export function gamut_compress_fwd(JMh: number[], p: ODTParams): number[] {
  const J: number = JMh[0]
  const M: number = JMh[1]
  const h: number = JMh[2]

  if (J <= 0.0) {
    let JMh: number[] = acesVec(0, 0, h)
    return JMh
  }

  if (M < 0 || J > p.limit_J_max) {
    let JMh: number[] = acesVec(J, 0, h)
    return JMh
  }

  let hdp: HueDependentGamutParams = init_HueDependentGamutParams(h, p)

  return compress_gamut(JMh, J, p, hdp, false)
}
export function any_below_zero(newLimitRGB: number[]): boolean {
  return newLimitRGB[0] < 0 || newLimitRGB[1] < 0 || newLimitRGB[2] < 0
}
export function init_JMhParams(prims: Chromaticities): JMhParams {
  const CAM16_PRI: Chromaticities = {
    red: [0.8336, 0.1735],
    green: [2.3854, -1.4659],
    blue: [0.087, -0.125],
    white: [0.333, 0.333],
  }

  const MATRIX_16: number[][] = XYZtoRGB_f33(CAM16_PRI, 1.0).map((r) => r.slice())

  const base_cone_response_to_Aab: number[][] = [
    [2, 1, 1 / 9],
    [1, -12 / 11, 1 / 9],
    [1 / 20, 1 / 11, -2 / 9],
  ]

  const RGB_TO_XYZ: number[][] = RGBtoXYZ_f33(prims, 1.0).map((r) => r.slice())
  const XYZ_w: number[] = mult_f3_f33(f3_from_f(ref_luminance), RGB_TO_XYZ).slice()

  let Y_w: number = XYZ_w[1]

  let RGB_w: number[] = mult_f3_f33(XYZ_w, MATRIX_16).slice()

  const k: number = 1 / (5 * L_A + 1)
  const k4: number = k * k * k * k
  const F_L: number = 0.2 * k4 * (5 * L_A) + 0.1 * Math.pow(1 - k4, 2) * Math.pow(5 * L_A, 1 / 3)

  const F_L_n: number = F_L / ref_luminance
  const cz: number = model_gamma

  const D_RGB: number[] = [
    (F_L_n * Y_w) / RGB_w[0],
    (F_L_n * Y_w) / RGB_w[1],
    (F_L_n * Y_w) / RGB_w[2],
  ]

  const RGB_wc: number[] = [D_RGB[0] * RGB_w[0], D_RGB[1] * RGB_w[1], D_RGB[2] * RGB_w[2]]

  const RGB_Aw: number[] = [
    post_adaptation_cone_response_compression_fwd(RGB_wc[0]),
    post_adaptation_cone_response_compression_fwd(RGB_wc[1]),
    post_adaptation_cone_response_compression_fwd(RGB_wc[2]),
  ]

  let cone_response_to_Aab: number[][] = mult_f33_f33(
    mult_f_f33(cam_nl_scale, MATRIX_IDENTITY),
    base_cone_response_to_Aab,
  ).map((r) => r.slice())
  let A_w: number =
    cone_response_to_Aab[0][0] * RGB_Aw[0] +
    cone_response_to_Aab[1][0] * RGB_Aw[1] +
    cone_response_to_Aab[2][0] * RGB_Aw[2]
  let A_w_J: number = _post_adaptation_cone_response_compression_fwd(F_L)

  let M1: number[][] = mult_f33_f33(RGB_TO_XYZ, MATRIX_16).map((r) => r.slice())
  let M2: number[][] = mult_f_f33(ref_luminance, MATRIX_IDENTITY).map((r) => r.slice())
  let MATRIX_RGB_to_CAM16: number[][] = mult_f33_f33(M1, M2).map((r) => r.slice())
  let MATRIX_RGB_to_CAM16_c: number[][] = mult_f33_f33(
    MATRIX_RGB_to_CAM16,
    scale_matrix_diagonal_f33_f3(MATRIX_IDENTITY, D_RGB),
  ).map((r) => r.slice())

  let MATRIX_cone_response_to_Aab: number[][] = [
    [
      cone_response_to_Aab[0][0] / A_w,
      cone_response_to_Aab[0][1] * 43 * surround[2],
      cone_response_to_Aab[0][2] * 43 * surround[2],
    ],
    [
      cone_response_to_Aab[1][0] / A_w,
      cone_response_to_Aab[1][1] * 43 * surround[2],
      cone_response_to_Aab[1][2] * 43 * surround[2],
    ],
    [
      cone_response_to_Aab[2][0] / A_w,
      cone_response_to_Aab[2][1] * 43 * surround[2],
      cone_response_to_Aab[2][2] * 43 * surround[2],
    ],
  ]

  let p: JMhParams = newJMhParams()
  p.MATRIX_RGB_to_CAM16_c = MATRIX_RGB_to_CAM16_c.map((r) => r.slice())
  p.MATRIX_CAM16_c_to_RGB = invert_f33(MATRIX_RGB_to_CAM16_c).map((r) => r.slice())
  p.MATRIX_cone_response_to_Aab = MATRIX_cone_response_to_Aab.map((r) => r.slice())
  p.MATRIX_Aab_to_cone_response = invert_f33(MATRIX_cone_response_to_Aab).map((r) => r.slice())
  p.F_L_n = F_L_n
  p.cz = cz
  p.inv_cz = 1 / cz
  p.A_w_J = A_w_J
  p.inv_A_w_J = 1 / A_w_J

  return p
}
export function generate_unit_cube_cusp_corners(corner: number): number[] {
  let result: number[] = Array.from({ length: 3 }, () => 0)

  if ((corner + 1) % cuspCornerCount < 3) result[0] = 1
  else result[0] = 0
  if ((corner + 5) % cuspCornerCount < 3) result[1] = 1
  else result[1] = 0
  if ((corner + 3) % cuspCornerCount < 3) result[2] = 1
  else result[2] = 0

  return result
}
export function build_limiting_cusp_corners_tables(
  RGB_corners: number[][],
  JMh_corners: number[][],
  params: JMhParams,
  peakLuminance: number,
): void {
  let temp_RGB_corners: number[][] = Array.from({ length: cuspCornerCount }, () =>
    Array.from({ length: 3 }, () => 0),
  )
  let temp_JMh_corners: number[][] = Array.from({ length: cuspCornerCount }, () =>
    Array.from({ length: 3 }, () => 0),
  )

  let min_index: number = Math.trunc(0)
  for (let i: number = Math.trunc(0); i != cuspCornerCount; i = i + 1) {
    temp_RGB_corners[i] = mult_f_f3(
      peakLuminance / ref_luminance,
      generate_unit_cube_cusp_corners(i),
    ).slice()
    temp_JMh_corners[i] = RGB_to_JMh(temp_RGB_corners[i], params).slice()
    if (temp_JMh_corners[i][2] < temp_JMh_corners[min_index][2]) min_index = Math.trunc(i)
  }

  for (let i: number = Math.trunc(0); i != cuspCornerCount; i = i + 1) {
    RGB_corners[i + 1] = temp_RGB_corners[(i + min_index) % cuspCornerCount].slice()
    JMh_corners[i + 1] = temp_JMh_corners[(i + min_index) % cuspCornerCount].slice()
  }

  RGB_corners[0] = RGB_corners[cuspCornerCount].slice()
  RGB_corners[cuspCornerCount + 1] = RGB_corners[1].slice()
  JMh_corners[0] = JMh_corners[cuspCornerCount].slice()
  JMh_corners[cuspCornerCount + 1] = JMh_corners[1].slice()

  JMh_corners[0][2] = JMh_corners[0][2] - hue_limit
  JMh_corners[cuspCornerCount + 1][2] = JMh_corners[cuspCornerCount + 1][2] + hue_limit
}
export function find_reach_corners_table(params_reach: JMhParams, p: ODTParams): number[][] {
  let temp_JMh_corners: number[][] = Array.from({ length: cuspCornerCount }, () =>
    Array.from({ length: 3 }, () => 0),
  )

  let JMh_corners: number[][] = Array.from({ length: totalCornerCount }, () =>
    Array.from({ length: 3 }, () => 0),
  )

  let limitA: number = J_to_Achromatic_n(p.limit_J_max, params_reach.inv_cz)

  let min_index: number = Math.trunc(0)
  for (let i: number = Math.trunc(0); i != cuspCornerCount; i = i + 1) {
    const rgb_vector: number[] = generate_unit_cube_cusp_corners(i).slice()

    let lower: number = 0.0
    let upper: number = p.ts.forward_limit

    while (upper - lower > reach_cusp_tolerance) {
      let test: number = (lower + upper) / 2
      let test_corner: number[] = mult_f_f3(test, rgb_vector).slice()
      let A: number = RGB_to_Aab(test_corner, params_reach)[0]
      if (A < limitA) {
        lower = test
      } else {
        upper = test
      }
    }

    temp_JMh_corners[i] = RGB_to_JMh(mult_f_f3(upper, rgb_vector), params_reach).slice()

    if (temp_JMh_corners[i][2] < temp_JMh_corners[min_index][2]) min_index = Math.trunc(i)
  }

  for (let i: number = Math.trunc(0); i != cuspCornerCount; i = i + 1) {
    JMh_corners[i + 1] = temp_JMh_corners[(i + min_index) % cuspCornerCount].slice()
  }

  JMh_corners[0] = JMh_corners[cuspCornerCount].slice()
  JMh_corners[cuspCornerCount + 1] = JMh_corners[1].slice()

  JMh_corners[0][2] = JMh_corners[0][2] - hue_limit
  JMh_corners[cuspCornerCount + 1][2] = JMh_corners[cuspCornerCount + 1][2] + hue_limit

  return JMh_corners
}
export function extract_sorted_cube_hues(reach_JMh: number[][], limit_JMh: number[][]): number[] {
  let sorted_hues: number[] = Array.from({ length: max_sorted_corners }, () => 0)

  let idx: number = Math.trunc(0)
  let reach_idx: number = Math.trunc(1)
  let limit_idx: number = Math.trunc(1)
  while (reach_idx < cuspCornerCount + 1 || limit_idx < cuspCornerCount + 1) {
    let reach_hue: number = reach_JMh[reach_idx][2]
    let limit_hue: number = limit_JMh[limit_idx][2]
    if (reach_hue == limit_hue) {
      sorted_hues[idx] = reach_hue
      reach_idx = Math.trunc(reach_idx + 1)
      limit_idx = Math.trunc(limit_idx + 1)
    } else {
      if (reach_hue < limit_hue) {
        sorted_hues[idx] = reach_hue
        reach_idx = Math.trunc(reach_idx + 1)
      } else {
        sorted_hues[idx] = limit_hue
        limit_idx = Math.trunc(limit_idx + 1)
      }
    }
    idx = Math.trunc(idx + 1)
  }
  return sorted_hues
}
export function build_hue_sample_interval(
  samples: number,
  lower: number,
  upper: number,
  hue_table: number[],
  base: number,
): number[] {
  let mod_hue_table: number[] = hue_table.slice()
  let delta: number = (upper - lower) / samples
  let i: number = 0
  for (i = Math.trunc(0); i != samples; i = i + 1) {
    mod_hue_table[base + i] = lower + i * delta
  }

  return mod_hue_table
}
export function build_hue_table(sorted_hues: number[]): number[] {
  let hue_table: number[] = Array.from({ length: totalTableSize }, () => 0)

  let ideal_spacing: number = tableSize / hue_limit
  let samples_count: number[] = Array.from({ length: 2 * cuspCornerCount + 2 }, () => 0)
  let last_idx: number = 0
  let min_index: number = 0
  if (sorted_hues[0] == 0.0) {
    min_index = Math.trunc(0)
  } else {
    min_index = Math.trunc(1)
  }
  let hue_idx: number = 0

  for (hue_idx = Math.trunc(0); hue_idx != max_sorted_corners; hue_idx = hue_idx + 1) {
    let nominal_idx: number = Math.trunc(
      Math.min(Math.max(roundCtl(sorted_hues[hue_idx] * ideal_spacing), min_index), tableSize - 1),
    )

    if (last_idx == nominal_idx) {
      if (hue_idx > 1 && samples_count[hue_idx - 2] != samples_count[hue_idx - 1] - 1) {
        samples_count[hue_idx - 1] = Math.trunc(samples_count[hue_idx - 1] - 1)
      } else {
        nominal_idx = Math.trunc(nominal_idx + 1)
      }
    }
    samples_count[hue_idx] = Math.trunc(Math.min(nominal_idx, tableSize - 1))
    min_index = Math.trunc(nominal_idx)
    last_idx = Math.trunc(min_index)
  }

  let total_samples: number = Math.trunc(0)

  let i: number = Math.trunc(0)
  hue_table = build_hue_sample_interval(
    samples_count[i],
    0.0,
    sorted_hues[i],
    hue_table,
    total_samples + 1,
  ).slice()
  total_samples = Math.trunc(total_samples + samples_count[i])

  for (i = Math.trunc(i + 1); i != max_sorted_corners; i = i + 1) {
    let samples: number = Math.trunc(samples_count[i] - samples_count[i - 1])
    hue_table = build_hue_sample_interval(
      samples,
      sorted_hues[i - 1],
      sorted_hues[i],
      hue_table,
      total_samples + 1,
    ).slice()
    total_samples = Math.trunc(total_samples + samples)
  }
  hue_table = build_hue_sample_interval(
    tableSize - total_samples,
    sorted_hues[i - 1],
    hue_limit,
    hue_table,
    total_samples + 1,
  ).slice()

  hue_table[0] = hue_table[baseIndex + tableSize - 1] - hue_limit
  hue_table[baseIndex + tableSize] = hue_table[baseIndex] + hue_limit

  return hue_table
}
export function find_display_cusp_for_hue(
  hue: number,
  RGB_corners: number[][],
  JMh_corners: number[][],
  params: JMhParams,
  previous: number[],
): number[] {
  let return_JM: number[] = Array.from({ length: 2 }, () => 0)

  let upper_corner: number = Math.trunc(1)
  let found: number = Math.trunc(0)
  for (let i: number = Math.trunc(upper_corner); i != totalCornerCount && !found; i = i + 1) {
    if (JMh_corners[i][2] > hue) {
      upper_corner = Math.trunc(i)
      found = Math.trunc(1)
    }
  }
  let lower_corner: number = Math.trunc(upper_corner - 1)

  if (JMh_corners[lower_corner][2] == hue) {
    return_JM[0] = JMh_corners[lower_corner][0]
    return_JM[1] = JMh_corners[lower_corner][1]
    return return_JM
  }

  let cusp_lower: number[] = RGB_corners[lower_corner].slice()
  let cusp_upper: number[] = RGB_corners[upper_corner].slice()
  let sample: number[] = Array.from({ length: 3 }, () => 0)

  let sample_t: number = 0
  let lower_t: number = 0.0
  if (upper_corner == previous[0]) lower_t = previous[1]
  let upper_t: number = 1.0

  let JMh: number[] = Array.from({ length: 3 }, () => 0)

  while (upper_t - lower_t > display_cusp_tolerance) {
    sample_t = midpoint(lower_t, upper_t)
    sample = lerp_f3(cusp_lower, cusp_upper, sample_t).slice()
    JMh = RGB_to_JMh(sample, params).slice()
    if (JMh[2] < JMh_corners[lower_corner][2]) {
      upper_t = sample_t
    } else if (JMh[2] >= JMh_corners[upper_corner][2]) {
      lower_t = sample_t
    } else if (JMh[2] > hue) {
      upper_t = sample_t
    } else {
      lower_t = sample_t
    }
  }

  sample_t = midpoint(lower_t, upper_t)
  sample = lerp_f3(cusp_lower, cusp_upper, sample_t).slice()
  JMh = RGB_to_JMh(sample, params).slice()

  return_JM[0] = JMh[0]
  return_JM[1] = JMh[1]
  return return_JM
}
export function build_cusp_table(
  hue_table: number[],
  RGB_corners: number[][],
  JMh_corners: number[][],
  params: JMhParams,
): number[][] {
  let previous: number[] = [0.0, 0.0]
  let output_table: number[][] = Array.from({ length: totalTableSize }, () =>
    Array.from({ length: 3 }, () => 0),
  )

  for (let i: number = Math.trunc(baseIndex); i != totalTableSize; i = i + 1) {
    let hue: number = hue_table[i]
    let JM: number[] = find_display_cusp_for_hue(
      hue,
      RGB_corners,
      JMh_corners,
      params,
      previous,
    ).slice()
    output_table[i][0] = JM[0]
    output_table[i][1] = JM[1] * (1 + smooth_m * smooth_cusps)
    output_table[i][2] = hue
  }

  output_table[0][0] = output_table[tableSize][0]
  output_table[0][1] = output_table[tableSize][1]
  output_table[0][2] = hue_table[0]

  output_table[baseIndex + tableSize][0] = output_table[baseIndex][0]
  output_table[baseIndex + tableSize][1] = output_table[baseIndex][1]
  output_table[baseIndex + tableSize][2] = hue_table[baseIndex + tableSize]

  return output_table
}
export function make_uniform_hue_gamut_table(
  reach_params: JMhParams,
  limit_params: JMhParams,
  p: ODTParams,
): number[][] {
  let reach_JMh_corners: number[][] = Array.from({ length: totalCornerCount }, () =>
    Array.from({ length: 3 }, () => 0),
  )
  let limiting_RGB_corners: number[][] = Array.from({ length: totalCornerCount }, () =>
    Array.from({ length: 3 }, () => 0),
  )
  let limiting_JMh_corners: number[][] = Array.from({ length: totalCornerCount }, () =>
    Array.from({ length: 3 }, () => 0),
  )

  reach_JMh_corners = find_reach_corners_table(reach_params, p).map((r) => r.slice())
  build_limiting_cusp_corners_tables(
    limiting_RGB_corners,
    limiting_JMh_corners,
    limit_params,
    p.peakLuminance,
  )
  let sorted_hues: number[] = extract_sorted_cube_hues(
    reach_JMh_corners,
    limiting_JMh_corners,
  ).slice()

  let hue_table: number[] = build_hue_table(sorted_hues).slice()

  let cusp_JMh_table: number[][] = build_cusp_table(
    hue_table,
    limiting_RGB_corners,
    limiting_JMh_corners,
    limit_params,
  ).map((r) => r.slice())

  return cusp_JMh_table
}
export function make_reach_m_table(params: JMhParams, limitJmax: number): number[] {
  let reachTable: number[] = Array.from({ length: totalTableSize }, () => 0)

  for (let i: number = Math.trunc(0); i < tableSize; i = i + 1) {
    let hue: number = base_hue_for_position(i, tableSize)

    const search_range: number = 50
    const search_maximum: number = 1300
    let low: number = 0
    let high: number = low + search_range
    let outside: boolean = false

    while (outside != true && high < search_maximum) {
      let searchJMh: number[] = [limitJmax, high, hue]
      let newLimitRGB: number[] = JMh_to_RGB(searchJMh, params).slice()
      outside = any_below_zero(newLimitRGB)
      if (outside == false) {
        low = high
        high = high + search_range
      }
    }

    while (high - low > 1e-2) {
      let sampleM: number = (high + low) / 2
      let searchJMh: number[] = [limitJmax, sampleM, hue]
      let newLimitRGB: number[] = JMh_to_RGB(searchJMh, params).slice()
      outside = any_below_zero(newLimitRGB)
      if (outside) {
        high = sampleM
      } else {
        low = sampleM
      }
    }

    reachTable[i + baseIndex] = high
  }

  reachTable[0] = reachTable[tableSize]

  reachTable[baseIndex + tableSize] = reachTable[baseIndex]

  return reachTable
}
export function outside_hull(rgb: number[], maxRGBtestVal: number): boolean {
  return rgb[0] > maxRGBtestVal || rgb[1] > maxRGBtestVal || rgb[2] > maxRGBtestVal
}
export function generate_gamma_test_data(
  JMcusp: number[],
  hue: number,
  limit_J_max: number,
  mid_J: number,
  focus_dist: number,
  test_JMh: number[][],
  J_intersect_source: number[],
  slopes: number[],
  J_intersect_cusp: number[],
): void {
  let analytical_threshold: number = lerp(JMcusp[0], limit_J_max, focus_gain_blend)
  let focus_J: number = compute_focus_J(JMcusp[0], mid_J, limit_J_max)

  for (let testIndex: number = Math.trunc(0); testIndex != test_count; testIndex = testIndex + 1) {
    let test_J: number = lerp(JMcusp[0], limit_J_max, testPositions[testIndex])
    let slope_gain: number = get_focus_gain(test_J, analytical_threshold, limit_J_max, focus_dist)
    let J_intersect: number = solve_J_intersect(test_J, JMcusp[1], focus_J, limit_J_max, slope_gain)
    let slope: number = compute_compression_vector_slope(
      J_intersect,
      focus_J,
      limit_J_max,
      slope_gain,
    )
    let J_cusp: number = solve_J_intersect(JMcusp[0], JMcusp[1], focus_J, limit_J_max, slope_gain)

    test_JMh[testIndex][0] = test_J
    test_JMh[testIndex][1] = JMcusp[1]
    test_JMh[testIndex][2] = hue
    J_intersect_source[testIndex] = J_intersect
    slopes[testIndex] = slope
    J_intersect_cusp[testIndex] = J_cusp
  }
}
export function evaluate_gamma_fit(
  JMcusp: number[],
  test_JMh: number[][],
  J_intersect_source: number[],
  slopes: number[],
  J_intersect_cusp: number[],
  top_gamma_inv: number,
  peakLuminance: number,
  limit_J_max: number,
  lower_hull_gamma_inv: number,
  limit_params: JMhParams,
): boolean {
  let luminance_limit: number = peakLuminance / ref_luminance

  for (let testIndex: number = Math.trunc(0); testIndex < test_count; testIndex = testIndex + 1) {
    let approxLimit_M: number = find_gamut_boundary_intersection(
      JMcusp,
      limit_J_max,
      top_gamma_inv,
      lower_hull_gamma_inv,
      J_intersect_source[testIndex],
      slopes[testIndex],
      J_intersect_cusp[testIndex],
    )
    let approxLimit_J: number = J_intersect_source[testIndex] + slopes[testIndex] * approxLimit_M

    let approximate_JMh: number[] = [approxLimit_J, approxLimit_M, test_JMh[testIndex][2]]

    let newLimitRGB: number[] = JMh_to_RGB(approximate_JMh, limit_params).slice()

    if (!outside_hull(newLimitRGB, luminance_limit)) return false
  }

  return true
}
export function make_upper_hull_gamma_table(gamutCuspTable: number[][], p: ODTParams): number[] {
  let upper_hull_gamma: number[] = Array.from({ length: totalTableSize }, () => 0)

  for (let i: number = Math.trunc(baseIndex); i != baseIndex + tableSize; i = i + 1) {
    let hue: number = gamutCuspTable[i][2]
    let JMcusp: number[] = [gamutCuspTable[i][0], gamutCuspTable[i][1]]

    let test_JMh: number[][] = Array.from({ length: test_count }, () =>
      Array.from({ length: 3 }, () => 0),
    )
    let J_intersect_source: number[] = Array.from({ length: test_count }, () => 0)
    let slopes: number[] = Array.from({ length: test_count }, () => 0)
    let J_intersect_cusp: number[] = Array.from({ length: test_count }, () => 0)

    generate_gamma_test_data(
      JMcusp,
      hue,
      p.limit_J_max,
      p.mid_J,
      p.focus_dist,
      test_JMh,
      J_intersect_source,
      slopes,
      J_intersect_cusp,
    )

    let search_range: number = gamma_search_step
    let low: number = gamma_minimum
    let high: number = low + search_range
    let outside: boolean = false
    while (!outside && high < gamma_maximum) {
      let gammaFound: boolean = evaluate_gamma_fit(
        JMcusp,
        test_JMh,
        J_intersect_source,
        slopes,
        J_intersect_cusp,
        1 / high,
        p.peakLuminance,
        p.limit_J_max,
        p.lower_hull_gamma_inv,
        p.limit_params,
      )
      if (!gammaFound) {
        low = high
        high = high + search_range
      } else {
        outside = true
      }
    }

    let testGamma: number = -1.0
    while (high - low > gamma_accuracy) {
      testGamma = midpoint(high, low)
      let gammaFound: boolean = evaluate_gamma_fit(
        JMcusp,
        test_JMh,
        J_intersect_source,
        slopes,
        J_intersect_cusp,
        1 / testGamma,
        p.peakLuminance,
        p.limit_J_max,
        p.lower_hull_gamma_inv,
        p.limit_params,
      )
      if (gammaFound) {
        high = testGamma
      } else {
        low = testGamma
      }
    }

    upper_hull_gamma[i] = 1 / high
  }

  upper_hull_gamma[0] = upper_hull_gamma[tableSize]

  upper_hull_gamma[tableSize + baseIndex] = upper_hull_gamma[baseIndex]

  return upper_hull_gamma
}
export function determine_hue_linearity_search_range(hue_table: number[]): number[] {
  const lower_padding: number = Math.trunc(0)
  const upper_padding: number = Math.trunc(1)

  let hue_linearity_search_range: number[] = [lower_padding, upper_padding]

  for (let i: number = Math.trunc(baseIndex); i != baseIndex + tableSize; i = i + 1) {
    const pos: number = Math.trunc(hue_position_in_uniform_table(hue_table[i], totalTableSize))
    const delta: number = Math.trunc(i - pos)
    hue_linearity_search_range[0] = Math.trunc(
      Math.min(hue_linearity_search_range[0], delta + lower_padding),
    )
    hue_linearity_search_range[1] = Math.trunc(
      Math.max(hue_linearity_search_range[1], delta + upper_padding),
    )
  }

  return hue_linearity_search_range
}
export function init_ODTParams(
  peakLuminance: number,
  limitingPrimaries: Chromaticities,
): ODTParams {
  let p: ODTParams = newODTParams()

  p.peakLuminance = peakLuminance

  p.input_params = init_JMhParams(AP0)
  p.reach_params = init_JMhParams(REACH_PRI)
  p.limit_params = init_JMhParams(limitingPrimaries)

  p.ts = init_TSParams(peakLuminance)

  p.limit_J_max = Y_to_J(peakLuminance, p.input_params)
  p.model_gamma_inv = 1 / model_gamma
  p.TABLE_reach_M = make_reach_m_table(p.reach_params, p.limit_J_max).slice()

  p.sat = Math.max(0.2, chroma_expand - chroma_expand * chroma_expand_fact * p.ts.log_peak)
  p.sat_thr = chroma_expand_thr / peakLuminance
  p.compr = chroma_compress + chroma_compress * chroma_compress_fact * p.ts.log_peak
  p.chroma_compress_scale = Math.pow(0.03379 * peakLuminance, 0.30596) - 0.45135

  p.mid_J = Y_to_J(p.ts.c_t * ref_luminance, p.input_params)
  p.focus_dist = focus_distance + focus_distance * focus_distance_scaling * p.ts.log_peak
  const lower_hull_gamma: number = 1.14 + 0.07 * p.ts.log_peak
  p.lower_hull_gamma_inv = 1 / lower_hull_gamma
  p.TABLE_gamut_cusps = make_uniform_hue_gamut_table(p.reach_params, p.limit_params, p).map((r) =>
    r.slice(),
  )
  for (let i: number = Math.trunc(0); i != totalTableSize; i = i + 1) {
    p.TABLE_hues[i] = p.TABLE_gamut_cusps[i][2]
  }
  p.TABLE_upper_hull_gamma = make_upper_hull_gamma_table(p.TABLE_gamut_cusps, p).slice()
  p.hue_linearity_search_range = determine_hue_linearity_search_range(p.TABLE_hues).slice()

  return p
}
export function outputTransform_fwd(aces: number[], p: ODTParams): number[] {
  let AP0_clamped: number[] = acesCopy(clamp_AP0_to_AP1(aces, 0, p.ts.forward_limit))

  let JMh: number[] = acesCopy(RGB_to_JMh(AP0_clamped, p.input_params))

  let tonemappedJMh: number[] = acesCopy(tonemap_and_compress_fwd(JMh, p))

  let compressedJMh: number[] = acesCopy(gamut_compress_fwd(tonemappedJMh, p))

  let RGBout: number[] = acesCopy(JMh_to_RGB(compressedJMh, p.limit_params))

  return RGBout
}
export function clamp(inputValue: number, clampMin: number, clampMax: number): number {
  return Math.max(clampMin, Math.min(inputValue, clampMax))
}
export function clamp_f3(inputValue: number[], clampMin: number, clampMax: number): number[] {
  let out: number[] = acesVec(0, 0, 0)
  out[0] = clamp(inputValue[0], clampMin, clampMax)
  out[1] = clamp(inputValue[1], clampMin, clampMax)
  out[2] = clamp(inputValue[2], clampMin, clampMax)

  return out
}
export function f3_from_f(a: number): number[] {
  let f3: number[] = [a, a, a]
  return f3
}
export function scale_matrix_diagonal_f33_f3(A: number[][], v: number[]): number[][] {
  let B: number[][] = A.map((r) => r.slice())
  B[0][0] = A[0][0] * v[0]
  B[1][1] = A[1][1] * v[1]
  B[2][2] = A[2][2] * v[2]
  return B
}
export function lerp(a: number, b: number, t: number): number {
  return a + t * (b - a)
}
export function lerp_f3(a: number[], b: number[], t: number): number[] {
  let lerped: number[] = [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)]
  return lerped
}
export function radians_to_degrees(radians: number): number {
  return (radians * 180.0) / M_PI
}
export function degrees_to_radians(degrees: number): number {
  return (degrees / 180.0) * M_PI
}
export function RGBtoXYZ_f33(C: Chromaticities, Y: number): number[][] {
  let X: number = (C.white[0] * Y) / C.white[1]
  let Z: number = ((1 - C.white[0] - C.white[1]) * Y) / C.white[1]

  let d: number =
    C.red[0] * (C.blue[1] - C.green[1]) +
    C.blue[0] * (C.green[1] - C.red[1]) +
    C.green[0] * (C.red[1] - C.blue[1])

  let Sr: number =
    (X * (C.blue[1] - C.green[1]) -
      C.green[0] * (Y * (C.blue[1] - 1) + C.blue[1] * (X + Z)) +
      C.blue[0] * (Y * (C.green[1] - 1) + C.green[1] * (X + Z))) /
    d

  let Sg: number =
    (X * (C.red[1] - C.blue[1]) +
      C.red[0] * (Y * (C.blue[1] - 1) + C.blue[1] * (X + Z)) -
      C.blue[0] * (Y * (C.red[1] - 1) + C.red[1] * (X + Z))) /
    d

  let Sb: number =
    (X * (C.green[1] - C.red[1]) -
      C.red[0] * (Y * (C.green[1] - 1) + C.green[1] * (X + Z)) +
      C.green[0] * (Y * (C.red[1] - 1) + C.red[1] * (X + Z))) /
    d

  let M: number[][] = Array.from({ length: 3 }, () => Array.from({ length: 3 }, () => 0))

  M[0][0] = Sr * C.red[0]
  M[0][1] = Sr * C.red[1]
  M[0][2] = Sr * (1 - C.red[0] - C.red[1])

  M[1][0] = Sg * C.green[0]
  M[1][1] = Sg * C.green[1]
  M[1][2] = Sg * (1 - C.green[0] - C.green[1])

  M[2][0] = Sb * C.blue[0]
  M[2][1] = Sb * C.blue[1]
  M[2][2] = Sb * (1 - C.blue[0] - C.blue[1])

  return M
}
export function XYZtoRGB_f33(C: Chromaticities, Y: number): number[][] {
  return invert_f33(RGBtoXYZ_f33(C, Y))
}
